# SPDX-License-Identifier: Apache-2.0
"""
Hook policy enforcement tests.

These tests run the *actual* installed hook scripts against synthetic payloads.
They catch bypass channels in the control surface — not agent behavior, but
the physics layer that determines whether a write succeeds or fails.

If any of these tests fail, enforcement is broken regardless of what the
agent is told to do.
"""

import json
import os
import subprocess
from pathlib import Path

import pytest

from governor.claude_hooks import (
    install_hook_scripts,
    create_approved_files_file,
    create_blocked_commands_file,
)


class HookHarness:
    """Shared setup + runner for hook policy tests."""

    @staticmethod
    def setup_project(
        tmp_path: Path,
        mode: str = "strict",
        approved: list[str] | None = None,
        blocked: list[str] | None = None,
    ) -> Path:
        """Create a governed project skeleton with real hook scripts."""
        gov_dir = tmp_path / ".governor"
        gov_dir.mkdir()
        (gov_dir / ".envelope").write_text(mode)
        create_approved_files_file(tmp_path, approved or [])
        if blocked is not None:
            create_blocked_commands_file(tmp_path, blocked)
        install_hook_scripts(tmp_path)
        return tmp_path

    @staticmethod
    def run_hook(project_dir: Path, payload: dict) -> subprocess.CompletedProcess:
        """Run the pre-tool hook with a JSON payload."""
        hook = project_dir / ".governor" / "hooks" / "pre_tool_use.py"
        return subprocess.run(
            ["python3", str(hook)],
            input=json.dumps(payload),
            capture_output=True,
            text=True,
            timeout=10,
            cwd=str(project_dir),
        )

    @staticmethod
    def assert_blocked(result: subprocess.CompletedProcess, reason_fragment: str = ""):
        """Assert the hook blocked the action."""
        assert result.returncode == 2, (
            f"Expected exit 2 (block), got {result.returncode}. "
            f"stdout={result.stdout!r}"
        )
        output = json.loads(result.stdout)
        assert output["decision"] == "block"
        if reason_fragment:
            assert reason_fragment in output.get("reason", ""), (
                f"Expected '{reason_fragment}' in reason, got: {output.get('reason')}"
            )

    @staticmethod
    def assert_allowed(result: subprocess.CompletedProcess):
        """Assert the hook allowed the action."""
        assert result.returncode == 0, (
            f"Expected exit 0 (allow), got {result.returncode}. "
            f"stdout={result.stdout!r}"
        )


# ── Delegated write payloads ──────────────────────────────────────────────
# These simulate "Agent A gets output from Agent B and tries to write it."
# The hook doesn't know or care about the source — it only sees the tool call.


class TestDelegatedWrite:
    """Claude receives Codex/other output and tries to write it."""

    def test_write_unapproved_file_blocked(self, tmp_path):
        """Agent receives generated code and writes to unapproved path."""
        project = HookHarness.setup_project(
            tmp_path, mode="strict", approved=["src/main.py"],
        )
        result = HookHarness.run_hook(project, {
            "tool_name": "Write",
            "tool_input": {
                "file_path": "src/generated_by_codex.py",
                "content": "# generated by codex\nprint('hello')",
            },
        })
        HookHarness.assert_blocked(result, "not pre-approved")

    def test_edit_unapproved_file_blocked(self, tmp_path):
        """Agent applies a patch from another agent to an unapproved file."""
        project = HookHarness.setup_project(
            tmp_path, mode="strict", approved=["src/main.py"],
        )
        result = HookHarness.run_hook(project, {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": "src/auth.py",
                "old_string": "pass",
                "new_string": "raise NotImplementedError",
            },
        })
        HookHarness.assert_blocked(result, "not pre-approved")

    def test_write_approved_file_allowed(self, tmp_path):
        """Agent writes to an explicitly approved file — should succeed."""
        project = HookHarness.setup_project(
            tmp_path, mode="strict", approved=["src/main.py"],
        )
        result = HookHarness.run_hook(project, {
            "tool_name": "Write",
            "tool_input": {
                "file_path": "src/main.py",
                "content": "# updated\n",
            },
        })
        HookHarness.assert_allowed(result)

    def test_notebook_edit_blocked(self, tmp_path):
        """NotebookEdit to unapproved file is also gated."""
        project = HookHarness.setup_project(
            tmp_path, mode="strict", approved=[],
        )
        result = HookHarness.run_hook(project, {
            "tool_name": "NotebookEdit",
            "tool_input": {
                "file_path": "notebook.ipynb",
                "cell_number": 0,
                "new_source": "import os",
            },
        })
        HookHarness.assert_blocked(result)


# ── Bash bypass attempts ──────────────────────────────────────────────────
# Agents that can't Write directly may try Bash to create files.


class TestBashBypass:
    """Agent tries to write files via Bash commands instead of Write tool."""

    def test_bash_heredoc_with_blocked_pattern(self, tmp_path):
        """Agent uses Bash with a blocked command pattern."""
        project = HookHarness.setup_project(
            tmp_path, mode="strict",
            blocked=["rm -rf", "cat >", "tee "],
        )
        result = HookHarness.run_hook(project, {
            "tool_name": "Bash",
            "tool_input": {
                "command": "cat > /tmp/evil.py << 'EOF'\nprint('pwned')\nEOF",
            },
        })
        HookHarness.assert_blocked(result, "Blocked command")

    def test_bash_tee_blocked(self, tmp_path):
        """Agent tries tee to write files."""
        project = HookHarness.setup_project(
            tmp_path, mode="strict",
            blocked=["tee "],
        )
        result = HookHarness.run_hook(project, {
            "tool_name": "Bash",
            "tool_input": {
                "command": "echo 'payload' | tee src/evil.py",
            },
        })
        HookHarness.assert_blocked(result, "Blocked command")

    def test_bash_safe_command_allowed(self, tmp_path):
        """Safe commands (pytest, ls, git) should pass."""
        project = HookHarness.setup_project(
            tmp_path, mode="strict",
            blocked=["rm -rf"],
        )
        result = HookHarness.run_hook(project, {
            "tool_name": "Bash",
            "tool_input": {"command": "python3 -m pytest tests/ -v"},
        })
        HookHarness.assert_allowed(result)


# ── Path normalization ────────────────────────────────────────────────────
# The real danger: approve "src/foo.py" and agent writes "src/../.ssh/config"
# These tests document current behavior and catch regressions.


class TestPathNormalization:
    """Test that path traversal doesn't bypass approval checks."""

    def test_dotdot_traversal_not_approved(self, tmp_path):
        """Path with .. that resolves outside approved scope should be blocked."""
        project = HookHarness.setup_project(
            tmp_path, mode="strict", approved=["src/main.py"],
        )
        result = HookHarness.run_hook(project, {
            "tool_name": "Write",
            "tool_input": {
                "file_path": "src/../.env",
                "content": "SECRET=leaked",
            },
        })
        # The hook does literal string matching: "src/../.env" != "src/main.py"
        # so this SHOULD be blocked
        HookHarness.assert_blocked(result, "not pre-approved")

    def test_dotdot_to_approved_file_not_matched(self, tmp_path):
        """src/../src/main.py should NOT match approved 'src/main.py' (literal match)."""
        project = HookHarness.setup_project(
            tmp_path, mode="strict", approved=["src/main.py"],
        )
        result = HookHarness.run_hook(project, {
            "tool_name": "Write",
            "tool_input": {
                "file_path": "src/../src/main.py",
                "content": "# updated",
            },
        })
        # Literal match: "src/../src/main.py" != "src/main.py"
        # This is correct behavior — don't normalize, block the ambiguity
        HookHarness.assert_blocked(result, "not pre-approved")

    def test_absolute_path_not_approved(self, tmp_path):
        """Absolute path should not match relative approval."""
        project = HookHarness.setup_project(
            tmp_path, mode="strict", approved=["src/main.py"],
        )
        result = HookHarness.run_hook(project, {
            "tool_name": "Write",
            "tool_input": {
                "file_path": "/home/user/project/src/main.py",
                "content": "# updated",
            },
        })
        HookHarness.assert_blocked(result, "not pre-approved")


# ── Exploratory mode boundary ─────────────────────────────────────────────
# Document what exploratory actually allows (answer in code, not vibes).


class TestExploratoryBoundary:
    """Exploratory mode = no file-write enforcement, only logging.

    This is intentional: exploratory is audit-only. If you want enforcement,
    use strict. These tests lock that semantic so it doesn't drift.
    """

    def test_exploratory_allows_any_write(self, tmp_path):
        """Exploratory allows writes to any file, approved or not."""
        project = HookHarness.setup_project(
            tmp_path, mode="exploratory", approved=[],
        )
        result = HookHarness.run_hook(project, {
            "tool_name": "Write",
            "tool_input": {"file_path": "anything.py", "content": "x"},
        })
        HookHarness.assert_allowed(result)

    def test_exploratory_still_blocks_commands(self, tmp_path):
        """Exploratory blocks dangerous commands even without file enforcement."""
        project = HookHarness.setup_project(
            tmp_path, mode="exploratory",
            blocked=["rm -rf"],
        )
        result = HookHarness.run_hook(project, {
            "tool_name": "Bash",
            "tool_input": {"command": "rm -rf /"},
        })
        HookHarness.assert_blocked(result, "Blocked command")

    def test_no_envelope_defaults_strict(self, tmp_path):
        """Missing envelope file → strict. No ambiguity."""
        gov_dir = tmp_path / ".governor"
        gov_dir.mkdir()
        create_approved_files_file(tmp_path, [])
        install_hook_scripts(tmp_path)
        # Deliberately do NOT create .envelope

        result = HookHarness.run_hook(tmp_path, {
            "tool_name": "Write",
            "tool_input": {"file_path": "evil.py", "content": "x"},
        })
        HookHarness.assert_blocked(result)

    def test_no_approved_list_strict_blocks_all(self, tmp_path):
        """Strict mode with no approved_files.json blocks all writes.

        This prevents the 'installed but inert' failure where hooks exist
        but don't actually gate anything because there's no list to check.
        """
        gov_dir = tmp_path / ".governor"
        gov_dir.mkdir()
        (gov_dir / ".envelope").write_text("strict")
        install_hook_scripts(tmp_path)
        # Deliberately do NOT create approved_files.json

        result = HookHarness.run_hook(tmp_path, {
            "tool_name": "Write",
            "tool_input": {"file_path": "anything.py", "content": "x"},
        })
        HookHarness.assert_blocked(result, "No approved_files.json")

    def test_no_approved_list_exploratory_allows(self, tmp_path):
        """Exploratory mode with no approved list still allows writes."""
        gov_dir = tmp_path / ".governor"
        gov_dir.mkdir()
        (gov_dir / ".envelope").write_text("exploratory")
        install_hook_scripts(tmp_path)
        # No approved_files.json

        result = HookHarness.run_hook(tmp_path, {
            "tool_name": "Write",
            "tool_input": {"file_path": "anything.py", "content": "x"},
        })
        HookHarness.assert_allowed(result)
