# SPDX-License-Identifier: Apache-2.0
"""Contract test: r2wire canonical JSON must be byte-identical to receipt_kernel.

If these tests fail, the two audit trails have diverged.  Fix the
canonicalizer, don't update the vectors.

Vectors are generated by gen_canonical_vectors.py using receipt_kernel
as the source of truth.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest


VECTORS_PATH = Path(__file__).resolve().parent / "data" / "canonical_vectors.json"


def _load_vectors() -> list[dict]:
    return json.loads(VECTORS_PATH.read_text(encoding="utf-8"))


class TestCanonicalVectors:
    """Assert byte-identical canonicalization: r2wire vs golden vectors."""

    def test_vectors_file_exists(self):
        assert VECTORS_PATH.exists(), (
            "Golden vectors missing. Run: "
            "PYTHONPATH=../receipt_kernel/src:src python3 tests/gen_canonical_vectors.py"
        )

    @pytest.mark.parametrize("vector", _load_vectors(), ids=lambda v: v["name"])
    def test_r2wire_matches_golden(self, vector):
        from r2wire.canonical import canonical_json_bytes

        obj = vector["input"]
        expected = vector["expected_utf8"].encode("utf-8")
        # nfc=False for kernel compat
        actual = canonical_json_bytes(obj, nfc=False)
        assert actual == expected, (
            f"r2wire drift for {vector['name']}:\n"
            f"  expected: {expected}\n"
            f"  actual:   {actual}"
        )


class TestCanonicalVectorsKernel:
    """Assert receipt_kernel still matches the golden vectors.

    If receipt_kernel changes its canonicalizer, these fail first.
    """

    @pytest.mark.parametrize("vector", _load_vectors(), ids=lambda v: v["name"])
    def test_kernel_matches_golden(self, vector):
        from receipt_kernel.envelope import canonical_json

        obj = vector["input"]
        expected = vector["expected_utf8"].encode("utf-8")
        actual = canonical_json(obj)
        assert actual == expected, (
            f"receipt_kernel drift for {vector['name']}:\n"
            f"  expected: {expected}\n"
            f"  actual:   {actual}"
        )


class TestR2WireEqualsKernel:
    """Direct comparison: r2wire(nfc=False) == receipt_kernel, same input."""

    @pytest.mark.parametrize("vector", _load_vectors(), ids=lambda v: v["name"])
    def test_byte_identical(self, vector):
        from receipt_kernel.envelope import canonical_json
        from r2wire.canonical import canonical_json_bytes

        obj = vector["input"]
        kernel = canonical_json(obj)
        r2 = canonical_json_bytes(obj, nfc=False)
        assert kernel == r2, f"diverged on {vector['name']}"
