# SPDX-License-Identifier: Apache-2.0
"""Tests for standing identity verification.

Cross-language conformance: fixtures are generated by the Rust standing-cli
(`standing identity create`). Python must produce identical verification
results for the same inputs.
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

from governor.standing.workload_identity import (
    AssessmentResult,
    StandingVerificationError,
    VerifiedIdentity,
    WorkloadId,
    _compute_signature,
    _to_rfc3339_signing,
    verify_and_resolve,
    verify_identity,
)

FIXTURES = Path(__file__).parent / "fixtures" / "standing"
SECRET = b"test-secret"


def _load_fixture(name: str) -> WorkloadId:
    data = json.loads((FIXTURES / name).read_text())
    return WorkloadId.from_dict(data)


def _issued_time(token: WorkloadId) -> datetime:
    """Parse issued_at to use as 'now' for expired tokens."""
    ts = token.issued_at.replace("Z", "+00:00")
    return datetime.fromisoformat(ts)


# ---------------------------------------------------------------------------
# Canonicalization
# ---------------------------------------------------------------------------

class TestCanonicalization:
    def test_z_to_plus_zero(self):
        assert _to_rfc3339_signing("2026-01-01T00:00:00Z") == "2026-01-01T00:00:00+00:00"

    def test_plus_zero_unchanged(self):
        assert _to_rfc3339_signing("2026-01-01T00:00:00+00:00") == "2026-01-01T00:00:00+00:00"

    def test_nanoseconds_preserved(self):
        assert _to_rfc3339_signing("2026-04-07T21:07:25.247857573Z") == "2026-04-07T21:07:25.247857573+00:00"


# ---------------------------------------------------------------------------
# Cross-language signature verification
# ---------------------------------------------------------------------------

class TestCrossLanguageSignature:
    def test_good_fixture_signature_matches(self):
        """Python computes the same signature as Rust for the good fixture."""
        token = _load_fixture("fixture_good.json")
        sig = _compute_signature(
            token.jti, token.name, token.location, token.audience,
            token.issued_at, token.expires_at, SECRET,
        )
        assert sig == token.signature

    def test_bad_aud_fixture_signature_matches(self):
        """Signature is valid even for wrong-audience tokens (signature is over all fields)."""
        token = _load_fixture("fixture_bad_aud.json")
        sig = _compute_signature(
            token.jti, token.name, token.location, token.audience,
            token.issued_at, token.expires_at, SECRET,
        )
        assert sig == token.signature

    def test_short_ttl_fixture_signature_matches(self):
        token = _load_fixture("fixture_short_ttl.json")
        sig = _compute_signature(
            token.jti, token.name, token.location, token.audience,
            token.issued_at, token.expires_at, SECRET,
        )
        assert sig == token.signature


# ---------------------------------------------------------------------------
# Verification (using fixtures from Rust)
# ---------------------------------------------------------------------------

class TestVerifyIdentity:
    def test_good_fixture_valid(self):
        token = _load_fixture("fixture_good.json")
        result = verify_identity(token, SECRET, now=_issued_time(token))
        assert result == AssessmentResult.VALID

    def test_wrong_secret_invalid_signature(self):
        token = _load_fixture("fixture_good.json")
        result = verify_identity(token, b"wrong", now=_issued_time(token))
        assert result == AssessmentResult.INVALID_SIGNATURE

    def test_tampered_name_invalid_signature(self):
        token = _load_fixture("fixture_good.json")
        token.name = "evil"
        result = verify_identity(token, SECRET, now=_issued_time(token))
        assert result == AssessmentResult.INVALID_SIGNATURE

    def test_wrong_audience_mismatch(self):
        token = _load_fixture("fixture_bad_aud.json")
        result = verify_identity(
            token, SECRET,
            expected_audience="standing",
            now=_issued_time(token),
        )
        assert result == AssessmentResult.AUDIENCE_MISMATCH

    def test_correct_audience_accepted(self):
        token = _load_fixture("fixture_bad_aud.json")
        result = verify_identity(
            token, SECRET,
            expected_audience="wrong-aud",
            now=_issued_time(token),
        )
        assert result == AssessmentResult.VALID

    def test_expired_token_rejected(self):
        token = _load_fixture("fixture_short_ttl.json")
        # 60s in the future, well past 1s TTL + 30s skew
        future = _issued_time(token) + timedelta(seconds=60)
        result = verify_identity(token, SECRET, now=future)
        assert result == AssessmentResult.EXPIRED

    def test_within_skew_accepted(self):
        token = _load_fixture("fixture_short_ttl.json")
        # 2s after issuance — past 1s TTL but within 30s skew
        near = _issued_time(token) + timedelta(seconds=2)
        result = verify_identity(token, SECRET, now=near)
        assert result == AssessmentResult.VALID

    def test_not_yet_valid(self):
        token = _load_fixture("fixture_good.json")
        # Verify from 60s in the past (beyond 30s skew)
        past = _issued_time(token) - timedelta(seconds=60)
        result = verify_identity(token, SECRET, now=past)
        assert result == AssessmentResult.NOT_YET_VALID

    def test_clock_divergence_compromised(self):
        token = _load_fixture("fixture_good.json")
        # Verifier 10 min behind issuer (beyond 300s max divergence)
        way_past = _issued_time(token) - timedelta(seconds=601)
        result = verify_identity(token, SECRET, now=way_past)
        assert result == AssessmentResult.ASSESSMENT_COMPROMISED

    def test_extreme_divergence_but_clearly_expired(self):
        token = _load_fixture("fixture_short_ttl.json")
        # Way in the future, clearly expired even under divergence
        way_future = _issued_time(token) + timedelta(seconds=1200)
        result = verify_identity(token, SECRET, now=way_future)
        assert result == AssessmentResult.EXPIRED


# ---------------------------------------------------------------------------
# Synthetic tokens (no Rust fixture needed)
# ---------------------------------------------------------------------------

class TestSyntheticTokens:
    def _make_token(self, **overrides) -> WorkloadId:
        now = datetime.now(timezone.utc)
        defaults = {
            "jti": "test-jti-123",
            "name": "bot",
            "location": "host-1",
            "audience": "standing",
            "issued_at": now.isoformat(),
            "expires_at": (now + timedelta(hours=1)).isoformat(),
        }
        defaults.update(overrides)
        sig = _compute_signature(
            defaults["jti"], defaults["name"], defaults["location"],
            defaults["audience"], defaults["issued_at"], defaults["expires_at"],
            SECRET,
        )
        defaults["signature"] = sig
        return WorkloadId(**defaults)

    def test_synthetic_valid(self):
        token = self._make_token()
        result = verify_identity(token, SECRET)
        assert result == AssessmentResult.VALID

    def test_temporal_incoherence_compromised(self):
        """expires_at before issued_at → compromised."""
        now = datetime.now(timezone.utc)
        token = self._make_token(
            issued_at=now.isoformat(),
            expires_at=(now - timedelta(hours=1)).isoformat(),
        )
        result = verify_identity(token, SECRET)
        assert result == AssessmentResult.ASSESSMENT_COMPROMISED

    def test_principal_id_format(self):
        token = self._make_token(name="deploy-bot", location="k8s-prod")
        assert token.principal_id == "wl:deploy-bot:k8s-prod"


# ---------------------------------------------------------------------------
# verify_and_resolve
# ---------------------------------------------------------------------------

class TestVerifyAndResolve:
    def test_returns_verified_identity(self):
        token = _load_fixture("fixture_good.json")
        vi = verify_and_resolve(token, SECRET, now=_issued_time(token))
        assert isinstance(vi, VerifiedIdentity)
        assert vi.principal_id == "wl:test-bot:host-1"
        assert vi.label == "test-bot"
        assert vi.audience == "standing"
        assert vi.jti == token.jti

    def test_fails_closed_on_bad_signature(self):
        token = _load_fixture("fixture_good.json")
        with pytest.raises(StandingVerificationError) as exc_info:
            verify_and_resolve(token, b"wrong", now=_issued_time(token))
        assert exc_info.value.result == AssessmentResult.INVALID_SIGNATURE

    def test_fails_closed_on_expired(self):
        token = _load_fixture("fixture_short_ttl.json")
        future = _issued_time(token) + timedelta(seconds=60)
        with pytest.raises(StandingVerificationError) as exc_info:
            verify_and_resolve(token, SECRET, now=future)
        assert exc_info.value.result == AssessmentResult.EXPIRED


# ---------------------------------------------------------------------------
# WorkloadId serialization
# ---------------------------------------------------------------------------

class TestWorkloadIdSerialization:
    def test_from_dict_roundtrip(self):
        token = _load_fixture("fixture_good.json")
        d = token.to_dict()
        token2 = WorkloadId.from_dict(d)
        assert token2.jti == token.jti
        assert token2.signature == token.signature

    def test_from_json(self):
        text = (FIXTURES / "fixture_good.json").read_text()
        token = WorkloadId.from_json(text)
        assert token.name == "test-bot"
