"""
Agent Governor for Agentic Development

A constraint system that makes AI coding agents production-safe by preventing
hallucination, maintaining architectural coherence, and enforcing evidence requirements.
"""

from .core import AgentGovernor
from .ledger import CodebaseLedger, CommitID
from .validators import Validator, FileValidator, Evidence
from .types import ProposalResult, Contradiction

# SQLite-backed multi-agent components
from .storage import Storage, Lease, get_storage
from .ledgers_v2 import (
    Fact,
    Decision,
    SQLiteFactLedger,
    SQLiteDecisionLedger,
    ConflictError,
    get_ledgers,
)
from .permissions import (
    AgentPermissions,
    PermissionManager,
    PROFILES as PERMISSION_PROFILES,
    create_default_config,
)

# Task management
from .tasks import (
    Task,
    TaskStatus,
    Priority,
    Label,
    Milestone,
    TimeEntry,
    Session,
    TaskManager,
    get_task_manager,
)

# Audit graph
from .graph import (
    Node,
    Edge,
    NodeType,
    EdgeType,
    AuditGraph,
    GraphBuilder,
    build_graph,
)

# Epistemic governance
from .epistemic import (
    Provenance,
    EvidenceType,
    EvidenceRef,
    GroundedClaim,
    GroundedClaimStatus,
    ClaimStatus,
    QUORUM_TO_CLAIM_STATUS,
    project_quorum_status,
    PromotionResult,
    EpistemicLedger,
    DEFAULT_CONFIDENCE,
    MAX_PEER_CONFIDENCE,
    HIGH_CONFIDENCE_THRESHOLD,
    CascadeEvent,
    PremiseCheckResult,
    TransitionReason,
    StatusTransition,
    TransitionResult,
    VALID_TRANSITIONS,
    is_valid_transition,
)

# Regime detection
from .regime import (
    OperationalRegime,
    RegimeSignals,
    RegimeThresholds,
    RegimeDetector,
    RegimeMetrics,
    SignalCollector,
)

# Boil control
from .boil import (
    ControlMode,
    BoilPreset,
    DwellState,
    BoilEvent,
    BoilController,
    PRESETS,
    list_presets,
    get_preset,
)

# Jurisdictions
from .jurisdictions import (
    SpilloverPolicy,
    ContradictionPolicy,
    BudgetProfile,
    Jurisdiction,
    JurisdictionState,
    JurisdictionManager,
    register_jurisdiction,
    get_jurisdiction,
    list_jurisdictions,
    get_all_jurisdictions,
    create_factual_jurisdiction,
    create_speculative_jurisdiction,
    create_adversarial_jurisdiction,
    create_narrative_jurisdiction,
)

# Security verifier
from .security import (
    VulnerabilityType,
    Severity,
    SecurityFinding,
    SecurityConfig,
    SecurityVerifier,
    quick_scan,
)

# Watch mode
from .watch import (
    FileState,
    FileChange,
    WatchEvent,
    WatchConfig,
    FileWatcher,
    WatchSession,
    watch_directory,
)

# Claude Code hooks
from .claude_hooks import (
    HookConfig,
    install_claude_hooks,
    uninstall_claude_hooks,
    get_hook_status,
)

# Direction tracking (landmarks, commitments, Δt)
from .direction import (
    CommitmentType,
    AnchorType,
    RelationType,
    ViolationSeverity,
    Commitment,
    Anchor,
    Relation,
    Trajectory,
    DeltaT,
    Violation,
    Triangle,
    BeliefGraph,
    DirectionLedger,
    create_direction_ledger,
    create_fiction_anchors,
    create_nonfiction_anchors,
    create_thesis_commitment,
    create_chekhov_commitment,
)

# Failure provenance & constraint hysteresis
from .scars import (
    FailureProvenance,
    Scar,
    Shield,
    FailureEvent,
    ScarConfig,
    ScarLedger,
    MAX_STIFFNESS,
    MIN_STIFFNESS,
    DEFAULT_ANNEAL_FLOOR,
    create_scar_ledger,
    classify_failure,
)

# Grounding audit pipeline
from .audit import (
    GroundingStatus,
    AuditStage,
    FailureMode,
    AuditDecision,
    AuditSeverity,
    AssertionScope,
    ClaimRisk,
    AuditResolution,
    DetectionSignals,
    GroundingAudit,
    PolicyEntry,
    PolicyStore,
    AuditPipeline,
    quick_audit,
    create_pipeline,
)

# Ultrastability (S₁ adaptive control)
from .ultrastability import (
    AdaptationVerdict,
    Pathology,
    ParameterDirection,
    ParameterSpec,
    RegulatoryParameters,
    EpochObservation,
    AdaptationRecord,
    AdaptationHistory,
    AdaptationTrigger,
    PathologyDetector,
    AdaptationDecision,
    UltrastabilityController,
    create_controller,
    create_default_parameters,
    observe_and_consider,
)

# Multi-agent routing
from .routing import (
    ModelTier,
    ComplexityEstimate,
    ComplexityEstimator,
    ModelCapabilities,
    ModelStatus,
    ModelRegistry,
    TaskRecord,
    TaskHistory,
    RoutingDecision,
    RoutingConfig,
    Router,
    create_router,
    estimate_complexity,
    recommend_tier,
)

# Homeostat (exploration budgets, adaptive gain scheduling)
from .homeostat import (
    HomeostatMode,
    ExplorationContext,
    EpistemicVitals,
    EpistemicSetpoints,
    TuningDelta,
    ExplorationBudget,
    ExplorationProfile,
    TuningGains,
    TuningClamps,
    ObservationRecord,
    Homeostat,
    EXPLORATION_PROFILES,
    get_profile,
    list_profiles,
    create_homeostat,
    create_setpoints,
    observe_and_tune,
)

# Coupling (Homeostat → Ultrastability one-way protocol)
from .coupling import (
    IntentVerdict,
    ParameterMapping,
    ParameterProposal,
    TuningIntent,
    ChangeResult,
    IntentOutcome,
    CouplingConfig,
    GovernorCoupling,
    DEFAULT_MAPPINGS,
    create_coupling,
)

# Drift detection (temporal asymmetry defense)
from .drift import (
    DriftFailureMode,
    DriftAlert,
    PremiseRecord,
    AgentActivity,
    DriftSignals,
    DriftThresholds,
    QuarantineConfig,
    PremiseQuarantine,
    DriftDetector,
    create_drift_detector,
    detect_drift,
)

# Strict programmer mode
from .strict import (
    ClaimCategory,
    CommitLevel,
    RiskLevel,
    ClaimRequirement,
    DEFAULT_REQUIREMENTS,
    DependencyContext,
    StrictPolicy,
    ClaimEvaluation,
    StrictModeGate,
    create_strict_policy,
    create_strict_setpoints,
    create_strict_boil_preset,
    create_strict_s1_overrides,
    create_strict_gate,
    quick_evaluate,
)

# Claim signal extraction
from .claim_signals import (
    SignalCategory,
    SignalMatch,
    ExtractionResult,
    ExtractionConfig,
    SignalExtractor,
    extract_signals,
    scan_text,
    has_implicit_claims,
    assertiveness_score,
    register_signals,
)

# TTL enforcement (recency decay)
from .ttl import (
    VolatilityClass,
    DecayAction,
    TTLPolicy,
    TrackedClaim,
    DecayEvent,
    RevalidationEntry,
    TTLManager,
    DEFAULT_POLICIES as DEFAULT_TTL_POLICIES,
    create_ttl_manager,
    # Layer 5: Revalidation orchestration
    RevalidationResult,
    RevalidationRun,
    RevalidationOrchestrator,
    create_revalidation_orchestrator,
)

# Dissent ledger (contradiction persistence)
from .dissent import (
    ObjectionSeverity,
    ObjectionStatus,
    BlockVerdict,
    EvidencePointer,
    Objection,
    ConfidenceSnapshot,
    ClaimDissentSummary,
    DissentLedger,
    create_dissent_ledger,
)

# Config profiles
from .profiles import (
    ProfileSettings,
    ProfileManager,
    BUILTIN_PROFILES,
    apply_profile,
    get_profile_manager,
)

# Code Autopilot (intent, profile config, overrides)
from .intent import (
    Intent,
    IntentProvenance,
    BRANCH_HEURISTICS,
    DEFAULT_PROFILE,
    get_intent,
    set_intent,
    clear_intent,
    resolve_intent,
    suggest_profile_for_branch,
    format_provenance,
)
from .autopilot import (
    ViolationDefault,
    ApprovalPath,
    EvidenceRequired,
    AnchorStrictness,
    ScopeEnforcement,
    ChangeLimit,
    ProfileConfig,
    AUTOPILOT_PROFILES,
    get_autopilot_profile,
    list_autopilot_profiles,
    apply_autopilot_profile,
    load_autopilot_config,
    resolve_violation_action,
    check_change_limits,
)
from .overrides import (
    OverrideReceipt,
    OverrideManager,
    parse_duration,
    create_override_manager,
    check_override,
)
from .continuity import (
    ConstraintClass,
    EnforcementAction,
    resolve_enforcement,
)

# Claim diff (epistemic state change detection)
from .claim_diff import (
    MutationType,
    ViolationType,
    MUTATION_SEVERITY,
    ClaimSnapshot,
    LedgerSnapshot,
    MutationEvent,
    ClaimPair,
    Violation as ClaimDiffViolation,
    DiffResult,
    DiffHistory,
    ClaimDiffer,
    snapshot_ledger,
    diff_snapshots,
    detect_laundering,
    detect_confidence_drift,
)

# Quorum state machine (multi-agent consensus)
from .quorum import (
    ClaimType as QuorumClaimType,
    VoteVerdict,
    QuorumStatus,
    QuorumPolicy,
    Vote,
    QuorumState,
    QuorumManager,
    DEFAULT_POLICIES as DEFAULT_QUORUM_POLICIES,
    create_quorum_manager,
    get_default_policy,
    RiskLevel as QuorumRiskLevel,
    TERMINAL_STATES,
    compute_fingerprint,
    # Layer 5: Roles & Scheduling
    AgentRole,
    RoleBudget,
    DEFAULT_ROLE_BUDGETS,
)

# Cooperative redundancy (independence scoring)
from .independence import (
    MethodSignature,
    IndependenceResult,
    IndependenceScorer,
    pairwise_jaccard,
    independence_score,
    is_independent_support,
)

# Semantic variety (post-commit text transform)
from .semvar import (
    MeaningTag,
    Register,
    PhraseEntry,
    SemVarConfig,
    PhraseMatch,
    TextInvariants,
    SemVarResult,
    PhraseBank,
    CooldownTracker,
    SemanticDiffGuard,
    SemVarEngine,
    extract_invariants,
)

# Puppet mode (persona pinning, semantic safety)
from .puppet import (
    CertaintyLevel,
    TagPosition,
    AnswerMode,
    DiffRuleId,
    DiffWarnId,
    RenderVerdict,
    FormattingRules,
    VoiceConstraints,
    HedgePolicy,
    VolatilityPolicy,
    EpistemicPosture,
    BehavioralConstraints,
    RoleDisclaimer,
    SafetyOverrides,
    PuppetProfile,
    SkeletonAtom,
    AnswerSkeleton,
    DiffViolation,
    DiffWarning,
    DiffGuardResult,
    PuppetRenderResult,
    PuppetDiffGuard,
    PuppetRenderer,
    PuppetRegistry,
    create_puppet_registry,
    create_puppet_renderer,
    render_with_puppet,
)

# Evidence persistence (Layer 1)
from .evidence_store import (
    RunProvenance,
    EvidenceStore,
    create_evidence_store,
)

# Tainted claim similarity (recurrence detection)
from .taint import (
    TaintType,
    FingerprintMethod,
    TaintVerdict,
    Fingerprint,
    TaintedClaim,
    TaintMatch,
    TaintCheckResult,
    TaintEvent,
    TaintConfig,
    TaintIndex,
    normalize as taint_normalize,
    fingerprint as taint_fingerprint,
    score as taint_score,
    create_taint_index,
    check_claim,
    taint_claim,
)

# Auto-tuning (threshold learning, reset tracking, setpoint calibration, budget sweep)
from .auto_tuning import (
    ResetType,
    TuningSuggestionKind,
    SweepMetric,
    CalibrationPhase,
    SignalDistribution,
    RegimeDistributions,
    ThresholdSuggestion,
    ThresholdAnalysis,
    ThresholdTuner,
    ResetRecord,
    ResetReport,
    ResetTracker,
    BaselineProfile,
    CalibrationResult,
    SetpointCalibrator,
    SweepPoint,
    SweepResult,
    BudgetSweeper,
    AutoTuner,
    create_auto_tuner,
    analyze_thresholds_from_metrics,
)

# Convergence tuning (offline system identification + proposal engine)
from .convergence_tuning import (
    TuningMode, TuningConfidence,
    ProposalStatus as TuningProposalStatus,
    ChangeSetType, RefactorSuggestionType, RollbackMetric, RollbackOperator,
    Regime as TuningRegime, Scope as TuningScope,
    TimeRange as TuningTimeRange, EvidenceWindow as TuningEvidenceWindow,
    ChangeParameterUpdate, ChangePatternUpdate, ChangeRefactorSuggestion,
    ChangeSet as TuningChangeSet,
    HardGuards, ObjectiveConstraints, Constraints as TuningConstraints,
    MetricsBlock, PredictedImpact, SummaryTable, ExampleEpisode,
    InterferenceEdge as TuningInterferenceEdge, SupportingEvidence,
    RollbackTrigger, TrialScope, EvaluationSet, TrialPlan,
    Approval as TuningApproval, TuningProposal, TuningApply,
    ProposalStore, PerAnchorAnalysis, ActionEffectiveness, TuningOpportunity,
    ConvergenceAnalyzer, AdmissibilityResult,
    check_regime_match, check_strength_non_regression,
    check_objective_constraints, check_trial_requirements,
    check_determinism_hygiene, check_admissibility,
    ConvergenceTuner, create_convergence_tuner,
    ACTION_AGGRESSIVENESS,
)

# Sybil resistance (bloc detection, Neff, origin budgets)
from .sybil import (
    SybilEventType,
    ProvenanceVector,
    Bloc,
    NeffResult,
    OriginBudget,
    SybilEvent,
    SybilConfig,
    BlocDetector,
    OriginBudgetTracker,
    SybilDetector,
    create_sybil_detector,
    compute_neff,
)

# Research mode (non-convergent epistemic control)
from .research import (
    HypothesisState,
    TerminalStateType,
    PromotionBlockReason,
    ResearchConfig,
    EvidenceImpulse,
    Hypothesis,
    TerminalState,
    EntropyCheckResult,
    DominanceCheckResult,
    DeltaTCheckResult,
    EntropyMonitor,
    DominanceMonitor,
    TimescaleMonitor,
    ResearchLedger,
    create_research_ledger,
    create_research_config,
)

# Unified check aggregation (VS Code extension integration)
from .check import (
    Position as CheckPosition,
    Range as CheckRange,
    CheckFinding,
    CheckResult,
    run_check,
    security_finding_to_check,
    continuity_violation_to_check,
)

# Continuity enforcement (Deferred 5: closed-loop generation control)
from .continuity import (
    AnchorType as ContinuityAnchorType,
    Severity as ContinuitySeverity,
    RecommendedAction,
    CorrectionLevel,
    Anchor as ContinuityAnchor,
    Violation as ContinuityViolation,
    ContinuityReport,
    AttemptLog,
    CorrectionConfig,
    ConvergenceBudget,
    ConvergenceResult,
    GenerationProvider,
    AnchorRegistry,
    ContinuityChecker,
    CorrectionLadder,
    DEFAULT_LADDER,
    ConvergenceExecutor,
    create_registry as create_continuity_registry,
    create_checker as create_continuity_checker,
    create_ladder as create_continuity_ladder,
    create_convergence_executor,
    check_output as check_continuity_output,
)

# Continuity bridges (mode-specific anchor integration)
from .continuity_bridges import (
    anchors_from_fiction_bible,
    anchors_from_characters,
    anchors_from_banned_tropes,
    anchors_from_world_rules,
    anchors_from_tone_settings,
    anchors_from_nonfiction_corpus,
    anchors_from_concepts,
    anchors_from_positions,
    anchors_from_puppet_profile,
)

# Violation resolver (W4: Interactive Violation Resolution)
from .violation_resolver import (
    ResolutionAction,
    ResolutionStatus,
    PendingViolation,
    ResolutionResult,
    ExceptionRecord,
    ViolationResolver,
    format_violation_prompt,
    get_mode_choices,
    create_resolver as create_violation_resolver,
)

# Evidence Gate (evidence-gated coding harness, formerly maude_lite)
from .evidence_gate import (
    MaudeLiteStatus,
    ClaimLevel,
    MaudeLiteClaim,
    MaudeLiteCitation,
    MaudeLiteInput,
    MaudeLiteOutput,
    CustodyScore,
    MaudeLiteConfig,
    MaudeLiteEvent,
    MaudeLiteLogger,
    MaudeLite,
    extract_claims,
    check_evidence,
    link_evidence_to_claims,
    detect_contradictions,
    score_custody,
    check_exit_shape,
    maude_lite_wrapper,
    BlockedError,
    check_output as check_maude_lite_output,
)

# Chrono check (temporal grounding)
from .chrono import (
    ChronoSeverity,
    ChronoFinding,
    check_chrono,
    check_chrono_strict,
    chrono_invariant_check,
    get_current_year,
)

# Identity check (name grounding)
from .identity import (
    IdentitySeverity,
    IdentityMatchType,
    IdentityFinding,
    IdentityConfig,
    check_identity,
    check_identity_strict,
    identity_invariant_check,
    load_identity_config,
)

# Governor adapters (Phase A4)
from .adapters import (
    AdapterFinding,
    AdapterConfig,
    ContentCheckFn,
    security_invariant,
    cfi_invariant,
    fiction_invariant,
    nonfiction_citation_invariant,
    tone_invariant,
    continuity_invariant,
    content_invariant,
    build_adapter_set,
)

# Invariant store (Deferred 1: invariant management)
from .invariant_store import (
    InvariantSpec,
    InvariantStore,
    VALID_KINDS,
)

# Context manager (Deferred 2: Web UI) - no external deps
from .context_manager import (
    GovernorContext,
    GovernorContextManager,
    VALID_MODES as CONTEXT_VALID_MODES,
)

# Chat bridge (Deferred 2: Web UI) - requires httpx (webui optional dep)
try:
    from .chat_bridge import (
        ChatMessage as BridgeChatMessage,
        ChatResponse as BridgeChatResponse,
        ChatChunk,
        ChatBackend,
        ChatBridge,
        GovernorHooks as BridgeGovernorHooks,
        OllamaBackend,
        AnthropicBackend,
        create_backend,
    )
except ImportError:
    pass

# Telemetry (Deferred 4, B2)
from .telemetry import (
    TelemetryEventType,
    TelemetryLevel,
    TelemetryConfig,
    TelemetryEvent,
    ProposalFields,
    VerificationFields,
    LLMCallFields,
    AutonomousIterationFields,
    ErrorFields,
    ContinuityTraceFields,
    ContinuityResultFields,
    CostReport,
    PerformanceReport,
    AnchorStats,
    ConvergenceReport,
    LogStats,
    StructuredLogger,
    TelemetryBackend,
    LoggingBackend,
    TelemetryCollector,
    analyze_costs,
    analyze_performance,
    analyze_convergence,
    export_events,
    get_collector,
    get_logger as get_telemetry_logger,
    hash_prompt,
)

# Autonomous execution (Phase A1-A2)
from .spine import (
    Spine,
    SpineViolation,
    SpineCheckResult,
    SpineManager,
)
from .invariants import (
    InvariantType,
    InvariantResult,
    Invariant,
    InvariantSet,
    InvariantLibrary,
)
from .execution import (
    StopReason,
    ExecutionStatus,
    ExecutionBudget,
    ExecutionUsage,
    ExecutionState,
    SessionManager,
)
from .executor import (
    StepResult,
    ExecutorConfig,
    ExecutionEvent,
    AutonomousExecutor,
)

# Control theory (R_t = PD/E)
from .control_theory import (
    Regime as RiskRegime,
    GovernorDecision,
    RiskAggregation,
    ToolPowerMetrics,
    FeedbackDelayComponents,
    EvidenceComponents,
    RiskCalculation,
    RiskWindow,
    PrivilegeTier,
    CapabilityEnvelope,
    ToolGateRequirements,
    OpenLoopMetrics,
    EpisodeRiskMetrics,
    ReceiptsCurrencyModel,
    GovernorCheckResult,
    RiskIndexEvent,
    CapabilityChangeEvent,
    RegimeTransitionEvent,
    GovernorDecisionEvent,
    OpenLoopDetectedEvent,
    GlassCannonDetectedEvent,
    EPSILON as RISK_EPSILON,
    DEFAULT_REGIME_THRESHOLDS,
    DEFAULT_TOOL_POWER,
    DEFAULT_E_MIN,
    DEFAULT_TAU,
    DEFAULT_DELAY,
    DEFAULT_PRIVILEGE_TIERS,
    compute_power,
    compute_delay,
    compute_evidence,
    compute_risk,
    classify_regime,
    update_ema,
    compute_sma,
    compute_worst_case,
    compute_p_max,
    select_privilege_tier,
    detect_open_loop,
    compute_sensitivity,
    aggregate_episode_risk,
    governor_check,
    RiskController,
)

# Instrumented Execution (AG2 Layer 0, Item #1)
from .instrument import (
    EventKind,
    ClaimModality,
    AG2ClaimType,
    DiffFinding,
    ActorKind,
    FindingSeverity,
    InstrumentProfile,
    Actor,
    Environment as InstrumentEnvironment,
    RepoState,
    ModelSpec,
    RunConfig,
    RunInputs,
    RunManifest,
    Event as InstrumentEvent,
    ArtifactReceipt,
    ClaimSource,
    ClaimScope,
    AG2Claim,
    ClaimDiffResult as AG2ClaimDiffResult,
    Waiver,
    ReportFinding,
    ReportProvenance,
    AG2Report,
    InstrumentConfig,
    ArtifactStore,
    RunStore,
    EventWriter,
    ClaimExtractor,
    AG2ClaimDiffer,
    ReportGenerator,
    RunVerifier,
    WaiverStore,
    InstrumentSystem,
    PytestParser,
    MypyParser,
    RuffParser,
    DEFAULT_TOOL_PARSERS,
)

# Slim Mode (AG2 Layer 0, Item #2)
from .slim_mode import (
    SlimMode,
    SlimStatus,
    ContradictionError,
    create_slim_mode,
)

# Envelopes — re-export SLIM mode addition
from .envelopes import EnvelopeMode, EnvelopeConfig

# Constraint Compiler (AG2 Layer 1, Item #3)
from .constraint_compiler import (
    ConstraintKind,
    ConstraintSeverity,
    ScarClass,
    OutputFormat as ConstraintOutputFormat,
    ResolvedConstraint,
    ConstraintSource,
    OverrideWarrant,
    QuorumUnsatisfiedReceipt,
    ConstraintBlock,
    ConstraintCache,
    ConstraintDiff,
    classify_scar,
    required_quorum,
    check_warrant_quorum,
    make_constraint_id,
    compute_priority as compute_constraint_priority,
    render_prompt_prefix,
    compile_constraints,
    diff_constraints,
    clear_cache as clear_constraint_cache,
    get_cache as get_constraint_cache,
)

from .detector_integration import (
    PhaseFlag,
    SignalQuality,
    GovernorAction,
    SignalKey,
    RawDetectorSignal,
    CollapsedSignal,
    SignalPolicy,
    SignalActionResult,
    DetectorSignalFile,
    DetectorIntegration,
    collapse_signal,
    map_signal_to_actions,
    failure_safe_signal,
    signal_to_constraints,
    make_evidence_ref,
    load_signal_file,
    save_signal_file,
)

from .commitment_transport import (
    Modality as TransportModality,
    CommitmentKind,
    TransportOutcome,
    Commitment as TransportCommitment,
    CommitmentTransport,
    ShearReport,
    TransportHistory,
    extract_commitments,
    validate_transport,
    check_transport,
    validate_compaction_transport,
    validate_bridge_transport,
    validate_constraint_transport,
    make_transport_event,
)

from .spectral_stability import (
    KineticRegion,
    GateVerdict,
    GovernanceLayer,
    CouplingHotspot,
    AdjacencyViolation,
    CouplingMatrix,
    StabilityReport,
    StabilityGate,
    build_coupling_matrix,
    check_adjacency,
    classify_region,
    determine_verdict,
    find_hotspots,
    compute_stability,
    make_stability_event,
)

from .scalar_collapse import (
    CollapseRisk,
    CollapseAction,
    MetricSample,
    CollapseSignals,
    CollapseReport,
    CollapseHistory,
    CollapseDetector,
    compute_signals,
    compute_collapse_risk,
    classify_risk as classify_collapse_risk,
    determine_action as determine_collapse_action,
    detect_collapse,
    make_collapse_event,
    DEFAULT_METRICS,
)

from .cli_chat import (
    ChatConfig,
    BackendInfo,
    ChatResult,
    CompareResult,
    probe_backends,
    probe_backend,
    run_chat,
    run_compare,
    parse_backend_spec,
    parse_backend_list,
    format_response as format_chat_response,
    format_compare as format_chat_compare,
    make_chat_event,
)

from .doc_governance import (
    DocScope,
    DocStatus,
    LinkKind,
    CheckSeverity as DocCheckSeverity,
    DocLink,
    GovDoc,
    AuthorityClaim,
    DocFinding,
    DocCheckResult,
    DocReceipt,
    StalenessReport,
    DocStore,
    DocGovernor,
    ExportConfig,
    extract_authority_claims,
    check_authority as check_doc_authority,
    check_adjacency as check_doc_adjacency,
    check_links as check_doc_links,
    check_staleness as check_doc_staleness,
    check_doc,
    generate_frontmatter,
    generate_sidecar,
    make_doc_event,
)

from .dashboard_ux import (
    StreamEventType,
    RunVerdict,
    RunState,
    ControlRender,
    CancelRequest,
    StreamEvent,
    RunTemplate,
    BUILTIN_TEMPLATES,
    ControlField,
    UIAction,
    BUILTIN_ACTIONS,
    RunSummary,
    DashboardSummary,
    ReportSection,
    RunReport,
    DashboardStore,
    build_controls_schema,
    generate_report as generate_run_report,
    make_heartbeat,
    make_progress,
    make_dashboard_event,
)

# WebUI Demo (AG2 Layer 4, Item #12)
from .webui_demo import (
    DemoSurface,
    StepAction,
    DemoStatus,
    DemoStep,
    DemoScenario,
    DemoManifest,
    DemoStore,
    BUILTIN_DEMOS,
    FICTION_VIOLATION_DEMO,
    CODE_GOVERNANCE_DEMO,
    INTERFEROMETRY_DEMO,
    generate_playwright_spec,
    make_demo_event,
)

# Epistemic Evasion (AG2 Layer 2.1-C)
from .epistemic_evasion import (
    EvasionOperator,
    FailureMode as EvasionFailureMode,
    EvasionSeverity,
    OperatorDetection,
    EvasionResult,
    EvasionState,
    EvasionStore,
    analyze_evasion,
    check_invariant_j,
    audit_governor_prompts,
    select_coupling_question,
    make_evasion_event,
)

# Mode Detection (AG2 Layer 2.1-C)
from .mode_detection import (
    DomainMode,
    DriftAction,
    DriftPhase,
    Observation as ModeObservation,
    ModePosterior,
    DriftAlert as ModeDriftAlert,
    ModeState,
    ModeDetectionStore,
    compute_mode_features,
    update_mode_posterior,
    compute_drift as compute_mode_drift,
    check_mode_drift,
    get_mode_profile,
    observe_and_update,
    make_mode_event,
)

# Hysteresis (AG2 Layer 2.1-C)
from .hysteresis import (
    HysteresisMode,
    TransitionVerdict,
    ReplanVerdict,
    RegressionSeverity,
    ModeTransitionResult,
    ReplanTracker,
    RegressionAlert,
    HysteresisState,
    HysteresisStore,
    compute_plan_hash,
    check_mode_transition,
    check_replan,
    detect_regressions,
    classify_regression_severity,
    check_invariant_k,
    make_hysteresis_event,
    make_transition_event,
    make_replan_event,
    make_regression_event,
)

# Quorum Extensions (AG2 Layer 2.1-D)
from .quorum_ext import (
    Severity as QuorumSeverity,
    QuorumCheckResult,
    AdjudicationAction,
    ConfirmerType,
    QuorumRequirement,
    Confirmation,
    Rejection,
    QuorumCheckDetail,
    AdjudicationRequest,
    QuorumExtState,
    QuorumExtStore,
    check_quorum as check_severity_quorum,
    check_two_man_rule,
    check_full_quorum,
    handle_disagreement,
    classify_severity,
    compute_fault_tolerance,
    make_quorum_ext_event,
    make_quorum_check_event,
    make_disagreement_event,
    make_two_man_event,
)

# Coherence Budget (AG2 Layer 2.1-C)
from .coherence_budget import (
    CBIStatus,
    ClosureDecision,
    CBIClaimStatus,
    CBIUnknownStatus,
    InvariantID,
    MetricID,
    CBIClaim,
    CBIUnknown,
    CBIResult,
    ClosureGateResult,
    CoherenceBudgetStore,
    compute_m1, compute_m2, compute_m3, compute_m4,
    compute_m5, compute_m6, compute_m7, compute_m8,
    compute_dt,
    attenuate_epistemic,
    compute_slow_hash,
    compute_drift_distance,
    compute_stability_score,
    compute_soft_score,
    compute_invariant_penalty,
    classify_cbi,
    compute_cbi,
    compute_uncertainty,
    check_closure_gate,
    check_passivity,
    confidence_cap,
    make_cbi_event,
)

# Risk Function (AG2 Layer 2.1-B)
from .risk_function import (
    RiskLevel,
    PolicyAction,
    RiskSignal,
    RiskWeights,
    RiskComponents,
    RiskAssessment,
    ThresholdCrossing,
    RiskState,
    RiskStore,
    compute_risk,
    classify_risk,
    apply_risk_policy,
    assess_risk,
    extract_untrusted_signal,
    extract_evidence_gap,
    extract_scope_signal,
    extract_irreversibility_signal,
    make_risk_event,
)

# Deployment Profiles (AG2 Layer 2.1-B)
from .deployment_profiles import (
    AuthorityClass,
    AuditLevel,
    ProposalStatus,
    RateLimit,
    CapabilityToken,
    DeploymentProfile,
    ActionProposal,
    DeploymentStore,
    PUBLIC_PROFILE,
    DELEGATED_PROFILE,
    OPERATOR_PROFILE,
    AUTONOMOUS_PROFILE,
    BUILTIN_PROFILES,
    check_tool_access,
    check_invariant_b,
    check_invariant_e,
    issue_token,
    propose_action,
    make_deployment_event,
)

# Measurement Integrity (AG2 Layer 2.1-B)
from .measurement_integrity import (
    TrustLevel,
    AlertType,
    FreezeReason,
    ToolOutput,
    TrustResult,
    Alert as MeasurementAlert,
    MeasurementState,
    MeasurementStore,
    is_trusted,
    detect_instruction_masquerade,
    evaluate_output,
    check_invariant_c,
    make_measurement_event,
)

# Phase Control (AG2 Layer 2.1-A)
from .phase_control import (
    Phase,
    TransitionResult,
    PhaseBudget,
    PhaseUsage,
    NoveltyDebt,
    RunState as PhaseRunState,
    PhaseTransitionEvent,
    PhaseController,
    PhaseStore,
    can_advance,
    check_budget,
    check_invariant_g,
    make_phase_event,
)

# Coverage Metrics (AG2 Layer 2.1-A)
from .metrics import (
    MetricSeverity,
    VerificationStatus,
    MetricClaim,
    ClaimCoverage,
    EfficiencyMetric,
    CoverageSnapshot,
    MetricsTracker,
    MetricsStore,
    compute_coverage,
    compute_coverage_by_severity,
    compute_efficiency,
    compute_claim_coverage,
    update_claim_status,
    make_metrics_event,
)

# Admissibility Gate (AG2 Layer 2.1-A)
from .admissibility import (
    Severity as AdmitSeverity,
    UnknownCategory,
    ResolvableBy,
    PushbackMode,
    AssumptionStatus,
    Unknown as AdmitUnknown,
    Assumption,
    AdmissibilityAssessment,
    Waiver as AdmitWaiver,
    AdmissibilityStore,
    select_pushback_mode,
    select_clarifying_questions,
    assess_task,
    check_invariant_f,
    make_admissibility_event,
)

__all__ = [
    # Legacy v0.1
    "AgentGovernor",
    "CodebaseLedger",
    "Commitment",
    "CommitID",
    "Validator",
    "FileValidator",
    "Evidence",
    "ProposalResult",
    "Contradiction",
    # Multi-agent (v2)
    "Storage",
    "Lease",
    "get_storage",
    "Fact",
    "Decision",
    "SQLiteFactLedger",
    "SQLiteDecisionLedger",
    "ConflictError",
    "get_ledgers",
    # Permissions
    "AgentPermissions",
    "PermissionManager",
    "PERMISSION_PROFILES",
    "create_default_config",
    # Task management
    "Task",
    "TaskStatus",
    "Priority",
    "Label",
    "Milestone",
    "TimeEntry",
    "Session",
    "TaskManager",
    "get_task_manager",
    # Audit graph
    "Node",
    "Edge",
    "NodeType",
    "EdgeType",
    "AuditGraph",
    "GraphBuilder",
    "build_graph",
    # Epistemic governance
    "Provenance",
    "EvidenceType",
    "EvidenceRef",
    "GroundedClaim",
    "GroundedClaimStatus",
    "ClaimStatus",
    "QUORUM_TO_CLAIM_STATUS",
    "project_quorum_status",
    "PromotionResult",
    "EpistemicLedger",
    "DEFAULT_CONFIDENCE",
    "MAX_PEER_CONFIDENCE",
    "HIGH_CONFIDENCE_THRESHOLD",
    "CascadeEvent",
    "PremiseCheckResult",
    "TransitionReason",
    "StatusTransition",
    "TransitionResult",
    "VALID_TRANSITIONS",
    "is_valid_transition",
    # Regime detection
    "OperationalRegime",
    "RegimeSignals",
    "RegimeThresholds",
    "RegimeDetector",
    "RegimeMetrics",
    "SignalCollector",
    # Boil control
    "ControlMode",
    "BoilPreset",
    "DwellState",
    "BoilEvent",
    "BoilController",
    "PRESETS",
    "list_presets",
    "get_preset",
    # Jurisdictions
    "SpilloverPolicy",
    "ContradictionPolicy",
    "BudgetProfile",
    "Jurisdiction",
    "JurisdictionState",
    "JurisdictionManager",
    "register_jurisdiction",
    "get_jurisdiction",
    "list_jurisdictions",
    "get_all_jurisdictions",
    "create_factual_jurisdiction",
    "create_speculative_jurisdiction",
    "create_adversarial_jurisdiction",
    "create_narrative_jurisdiction",
    # Security verifier
    "VulnerabilityType",
    "Severity",
    "SecurityFinding",
    "SecurityConfig",
    "SecurityVerifier",
    "quick_scan",
    # Watch mode
    "FileState",
    "FileChange",
    "WatchEvent",
    "WatchConfig",
    "FileWatcher",
    "WatchSession",
    "watch_directory",
    # Claude Code hooks
    "HookConfig",
    "install_claude_hooks",
    "uninstall_claude_hooks",
    "get_hook_status",
    # Direction tracking
    "CommitmentType",
    "AnchorType",
    "RelationType",
    "ViolationSeverity",
    "Commitment",
    "Anchor",
    "Relation",
    "Trajectory",
    "DeltaT",
    "Violation",
    "Triangle",
    "BeliefGraph",
    "DirectionLedger",
    "create_direction_ledger",
    "create_fiction_anchors",
    "create_nonfiction_anchors",
    "create_thesis_commitment",
    "create_chekhov_commitment",
    # Failure provenance & constraint hysteresis
    "FailureProvenance",
    "Scar",
    "Shield",
    "FailureEvent",
    "ScarConfig",
    "ScarLedger",
    "MAX_STIFFNESS",
    "MIN_STIFFNESS",
    "DEFAULT_ANNEAL_FLOOR",
    "create_scar_ledger",
    "classify_failure",
    # Grounding audit pipeline
    "GroundingStatus",
    "AuditStage",
    "FailureMode",
    "AuditDecision",
    "AuditSeverity",
    "AssertionScope",
    "ClaimRisk",
    "AuditResolution",
    "DetectionSignals",
    "GroundingAudit",
    "PolicyEntry",
    "PolicyStore",
    "AuditPipeline",
    "quick_audit",
    "create_pipeline",
    # Ultrastability (S₁ adaptive control)
    "AdaptationVerdict",
    "Pathology",
    "ParameterDirection",
    "ParameterSpec",
    "RegulatoryParameters",
    "EpochObservation",
    "AdaptationRecord",
    "AdaptationHistory",
    "AdaptationTrigger",
    "PathologyDetector",
    "AdaptationDecision",
    "UltrastabilityController",
    "create_controller",
    "create_default_parameters",
    "observe_and_consider",
    # Multi-agent routing
    "ModelTier",
    "ComplexityEstimate",
    "ComplexityEstimator",
    "ModelCapabilities",
    "ModelStatus",
    "ModelRegistry",
    "TaskRecord",
    "TaskHistory",
    "RoutingDecision",
    "RoutingConfig",
    "Router",
    "create_router",
    "estimate_complexity",
    "recommend_tier",
    # Homeostat (exploration budgets)
    "HomeostatMode",
    "ExplorationContext",
    "EpistemicVitals",
    "EpistemicSetpoints",
    "TuningDelta",
    "ExplorationBudget",
    "ExplorationProfile",
    "TuningGains",
    "TuningClamps",
    "ObservationRecord",
    "Homeostat",
    "EXPLORATION_PROFILES",
    "get_profile",
    "list_profiles",
    "create_homeostat",
    "create_setpoints",
    "observe_and_tune",
    # Coupling (Homeostat → Ultrastability)
    "IntentVerdict",
    "ParameterMapping",
    "ParameterProposal",
    "TuningIntent",
    "ChangeResult",
    "IntentOutcome",
    "GovernorCoupling",
    "CouplingConfig",
    "DEFAULT_MAPPINGS",
    "create_coupling",
    # Drift detection (temporal asymmetry defense)
    "DriftFailureMode",
    "DriftAlert",
    "PremiseRecord",
    "AgentActivity",
    "DriftSignals",
    "DriftThresholds",
    "QuarantineConfig",
    "PremiseQuarantine",
    "DriftDetector",
    "create_drift_detector",
    "detect_drift",
    # Strict programmer mode
    "ClaimCategory",
    "CommitLevel",
    "RiskLevel",
    "ClaimRequirement",
    "DEFAULT_REQUIREMENTS",
    "DependencyContext",
    "StrictPolicy",
    "ClaimEvaluation",
    "StrictModeGate",
    "create_strict_policy",
    "create_strict_setpoints",
    "create_strict_boil_preset",
    "create_strict_s1_overrides",
    "create_strict_gate",
    "quick_evaluate",
    # Claim signal extraction
    "SignalCategory",
    "SignalMatch",
    "ExtractionResult",
    "ExtractionConfig",
    "SignalExtractor",
    "extract_signals",
    "scan_text",
    "has_implicit_claims",
    "assertiveness_score",
    "register_signals",
    # TTL enforcement (recency decay)
    "VolatilityClass",
    "DecayAction",
    "TTLPolicy",
    "TrackedClaim",
    "DecayEvent",
    "RevalidationEntry",
    "TTLManager",
    "DEFAULT_TTL_POLICIES",
    "create_ttl_manager",
    "RevalidationResult",
    "RevalidationRun",
    "RevalidationOrchestrator",
    "create_revalidation_orchestrator",
    # Dissent ledger (contradiction persistence)
    "ObjectionSeverity",
    "ObjectionStatus",
    "BlockVerdict",
    "EvidencePointer",
    "Objection",
    "ConfidenceSnapshot",
    "ClaimDissentSummary",
    "DissentLedger",
    "create_dissent_ledger",
    # Config profiles
    "ProfileSettings",
    "ProfileManager",
    "BUILTIN_PROFILES",
    "apply_profile",
    "get_profile_manager",
    # Code Autopilot (intent, profile config, overrides)
    "Intent",
    "IntentProvenance",
    "BRANCH_HEURISTICS",
    "DEFAULT_PROFILE",
    "get_intent",
    "set_intent",
    "clear_intent",
    "resolve_intent",
    "suggest_profile_for_branch",
    "format_provenance",
    "ViolationDefault",
    "ApprovalPath",
    "EvidenceRequired",
    "AnchorStrictness",
    "ScopeEnforcement",
    "ChangeLimit",
    "ProfileConfig",
    "AUTOPILOT_PROFILES",
    "get_autopilot_profile",
    "list_autopilot_profiles",
    "apply_autopilot_profile",
    "load_autopilot_config",
    "resolve_violation_action",
    "check_change_limits",
    "OverrideReceipt",
    "OverrideManager",
    "parse_duration",
    "create_override_manager",
    "check_override",
    "ConstraintClass",
    "EnforcementAction",
    "resolve_enforcement",
    # Claim diff (epistemic state change detection)
    "MutationType",
    "ViolationType",
    "MUTATION_SEVERITY",
    "ClaimSnapshot",
    "LedgerSnapshot",
    "MutationEvent",
    "ClaimPair",
    "ClaimDiffViolation",
    "DiffResult",
    "DiffHistory",
    "ClaimDiffer",
    "snapshot_ledger",
    "diff_snapshots",
    "detect_laundering",
    "detect_confidence_drift",
    # Quorum state machine (multi-agent consensus)
    "QuorumClaimType",
    "VoteVerdict",
    "QuorumStatus",
    "QuorumPolicy",
    "Vote",
    "QuorumState",
    "QuorumManager",
    "DEFAULT_QUORUM_POLICIES",
    "create_quorum_manager",
    "get_default_policy",
    "QuorumRiskLevel",
    "TERMINAL_STATES",
    "compute_fingerprint",
    "AgentRole",
    "RoleBudget",
    "DEFAULT_ROLE_BUDGETS",
    # Cooperative redundancy (independence scoring)
    "MethodSignature",
    "IndependenceResult",
    "IndependenceScorer",
    "pairwise_jaccard",
    "independence_score",
    "is_independent_support",
    # Semantic variety (post-commit text transform)
    "MeaningTag",
    "Register",
    "PhraseEntry",
    "SemVarConfig",
    "PhraseMatch",
    "TextInvariants",
    "SemVarResult",
    "PhraseBank",
    "CooldownTracker",
    "SemanticDiffGuard",
    "SemVarEngine",
    "extract_invariants",
    # Puppet mode (persona pinning, semantic safety)
    "CertaintyLevel",
    "TagPosition",
    "AnswerMode",
    "DiffRuleId",
    "DiffWarnId",
    "RenderVerdict",
    "FormattingRules",
    "VoiceConstraints",
    "HedgePolicy",
    "VolatilityPolicy",
    "EpistemicPosture",
    "BehavioralConstraints",
    "RoleDisclaimer",
    "SafetyOverrides",
    "PuppetProfile",
    "SkeletonAtom",
    "AnswerSkeleton",
    "DiffViolation",
    "DiffWarning",
    "DiffGuardResult",
    "PuppetRenderResult",
    "PuppetDiffGuard",
    "PuppetRenderer",
    "PuppetRegistry",
    "create_puppet_registry",
    "create_puppet_renderer",
    "render_with_puppet",
    # Evidence persistence (Layer 1)
    "RunProvenance",
    "EvidenceStore",
    "create_evidence_store",
    # Tainted claim similarity (recurrence detection)
    "TaintType",
    "FingerprintMethod",
    "TaintVerdict",
    "Fingerprint",
    "TaintedClaim",
    "TaintMatch",
    "TaintCheckResult",
    "TaintEvent",
    "TaintConfig",
    "TaintIndex",
    "taint_normalize",
    "taint_fingerprint",
    "taint_score",
    "create_taint_index",
    "check_claim",
    "taint_claim",
    # Auto-tuning (threshold learning, reset tracking, calibration, sweep)
    "ResetType",
    "TuningSuggestionKind",
    "SweepMetric",
    "CalibrationPhase",
    "SignalDistribution",
    "RegimeDistributions",
    "ThresholdSuggestion",
    "ThresholdAnalysis",
    "ThresholdTuner",
    "ResetRecord",
    "ResetReport",
    "ResetTracker",
    "BaselineProfile",
    "CalibrationResult",
    "SetpointCalibrator",
    "SweepPoint",
    "SweepResult",
    "BudgetSweeper",
    "AutoTuner",
    "create_auto_tuner",
    "analyze_thresholds_from_metrics",
    # Convergence tuning (offline system identification + proposal engine)
    "TuningMode",
    "TuningConfidence",
    "TuningProposalStatus",
    "ChangeSetType",
    "RefactorSuggestionType",
    "RollbackMetric",
    "RollbackOperator",
    "TuningRegime",
    "TuningScope",
    "TuningTimeRange",
    "TuningEvidenceWindow",
    "ChangeParameterUpdate",
    "ChangePatternUpdate",
    "ChangeRefactorSuggestion",
    "TuningChangeSet",
    "HardGuards",
    "ObjectiveConstraints",
    "TuningConstraints",
    "MetricsBlock",
    "PredictedImpact",
    "SummaryTable",
    "ExampleEpisode",
    "TuningInterferenceEdge",
    "SupportingEvidence",
    "RollbackTrigger",
    "TrialScope",
    "EvaluationSet",
    "TrialPlan",
    "TuningApproval",
    "TuningProposal",
    "TuningApply",
    "ProposalStore",
    "PerAnchorAnalysis",
    "ActionEffectiveness",
    "TuningOpportunity",
    "ConvergenceAnalyzer",
    "AdmissibilityResult",
    "check_regime_match",
    "check_strength_non_regression",
    "check_objective_constraints",
    "check_trial_requirements",
    "check_determinism_hygiene",
    "check_admissibility",
    "ConvergenceTuner",
    "create_convergence_tuner",
    "ACTION_AGGRESSIVENESS",
    # Sybil resistance (bloc detection, Neff, origin budgets)
    "SybilEventType",
    "ProvenanceVector",
    "Bloc",
    "NeffResult",
    "OriginBudget",
    "SybilEvent",
    "SybilConfig",
    "BlocDetector",
    "OriginBudgetTracker",
    "SybilDetector",
    "create_sybil_detector",
    "compute_neff",
    # Research mode (non-convergent epistemic control)
    "HypothesisState",
    "TerminalStateType",
    "PromotionBlockReason",
    "ResearchConfig",
    "EvidenceImpulse",
    "Hypothesis",
    "TerminalState",
    "EntropyCheckResult",
    "DominanceCheckResult",
    "DeltaTCheckResult",
    "EntropyMonitor",
    "DominanceMonitor",
    "TimescaleMonitor",
    "ResearchLedger",
    "create_research_ledger",
    "create_research_config",
    # Unified check aggregation (VS Code extension)
    "CheckPosition",
    "CheckRange",
    "CheckFinding",
    "CheckResult",
    "run_check",
    "security_finding_to_check",
    "continuity_violation_to_check",
    # Continuity enforcement (Deferred 5)
    "ContinuityAnchorType",
    "ContinuitySeverity",
    "RecommendedAction",
    "CorrectionLevel",
    "ContinuityAnchor",
    "ContinuityViolation",
    "ContinuityReport",
    "AttemptLog",
    "CorrectionConfig",
    "ConvergenceBudget",
    "ConvergenceResult",
    "GenerationProvider",
    "AnchorRegistry",
    "ContinuityChecker",
    "CorrectionLadder",
    "DEFAULT_LADDER",
    "ConvergenceExecutor",
    "create_continuity_registry",
    "create_continuity_checker",
    "create_continuity_ladder",
    "create_convergence_executor",
    "check_continuity_output",
    # Continuity bridges (mode-specific anchor integration)
    "anchors_from_fiction_bible",
    "anchors_from_characters",
    "anchors_from_banned_tropes",
    "anchors_from_world_rules",
    "anchors_from_tone_settings",
    "anchors_from_nonfiction_corpus",
    "anchors_from_concepts",
    "anchors_from_positions",
    "anchors_from_puppet_profile",
    # Maude Lite (evidence-gated coding harness)
    "MaudeLiteStatus",
    "ClaimLevel",
    "MaudeLiteClaim",
    "MaudeLiteCitation",
    "MaudeLiteInput",
    "MaudeLiteOutput",
    "CustodyScore",
    "MaudeLiteConfig",
    "MaudeLiteEvent",
    "MaudeLiteLogger",
    "MaudeLite",
    "extract_claims",
    "check_evidence",
    "link_evidence_to_claims",
    "detect_contradictions",
    "score_custody",
    "check_exit_shape",
    "maude_lite_wrapper",
    "BlockedError",
    "check_maude_lite_output",
    # Chrono check (temporal grounding)
    "ChronoSeverity",
    "ChronoFinding",
    "check_chrono",
    "check_chrono_strict",
    "chrono_invariant_check",
    "get_current_year",
    # Identity check (name grounding)
    "IdentitySeverity",
    "IdentityMatchType",
    "IdentityFinding",
    "IdentityConfig",
    "check_identity",
    "check_identity_strict",
    "identity_invariant_check",
    "load_identity_config",
    # Violation resolver (W4: Interactive Violation Resolution)
    "ResolutionAction",
    "ResolutionStatus",
    "PendingViolation",
    "ResolutionResult",
    "ExceptionRecord",
    "ViolationResolver",
    "format_violation_prompt",
    "get_mode_choices",
    "create_violation_resolver",
    # Governor adapters (Phase A4)
    "AdapterFinding",
    "AdapterConfig",
    "ContentCheckFn",
    "security_invariant",
    "cfi_invariant",
    "fiction_invariant",
    "nonfiction_citation_invariant",
    "tone_invariant",
    "continuity_invariant",
    "content_invariant",
    "build_adapter_set",
    # Invariant store (Deferred 1)
    "InvariantSpec",
    "InvariantStore",
    "VALID_KINDS",
    # Context manager & chat bridge (Deferred 2: Web UI)
    "GovernorContext",
    "GovernorContextManager",
    "CONTEXT_VALID_MODES",
    "BridgeChatMessage",
    "BridgeChatResponse",
    "ChatChunk",
    "ChatBackend",
    "ChatBridge",
    "BridgeGovernorHooks",
    "OllamaBackend",
    "AnthropicBackend",
    "create_backend",
    # Autonomous execution (Phase A1-A2)
    "Spine",
    "SpineViolation",
    "SpineCheckResult",
    "SpineManager",
    "InvariantType",
    "InvariantResult",
    "Invariant",
    "InvariantSet",
    "InvariantLibrary",
    "StopReason",
    "ExecutionStatus",
    "ExecutionBudget",
    "ExecutionUsage",
    "ExecutionState",
    "SessionManager",
    "StepResult",
    "ExecutorConfig",
    "ExecutionEvent",
    "AutonomousExecutor",
    # Control theory (R_t = PD/E)
    "RiskRegime",
    "GovernorDecision",
    "RiskAggregation",
    "ToolPowerMetrics",
    "FeedbackDelayComponents",
    "EvidenceComponents",
    "RiskCalculation",
    "RiskWindow",
    "PrivilegeTier",
    "CapabilityEnvelope",
    "ToolGateRequirements",
    "OpenLoopMetrics",
    "EpisodeRiskMetrics",
    "ReceiptsCurrencyModel",
    "GovernorCheckResult",
    "RiskIndexEvent",
    "CapabilityChangeEvent",
    "RegimeTransitionEvent",
    "GovernorDecisionEvent",
    "OpenLoopDetectedEvent",
    "GlassCannonDetectedEvent",
    "RISK_EPSILON",
    "DEFAULT_REGIME_THRESHOLDS",
    "DEFAULT_TOOL_POWER",
    "DEFAULT_E_MIN",
    "DEFAULT_TAU",
    "DEFAULT_DELAY",
    "DEFAULT_PRIVILEGE_TIERS",
    "compute_power",
    "compute_delay",
    "compute_evidence",
    "compute_risk",
    "classify_regime",
    "update_ema",
    "compute_sma",
    "compute_worst_case",
    "compute_p_max",
    "select_privilege_tier",
    "detect_open_loop",
    "compute_sensitivity",
    "aggregate_episode_risk",
    "governor_check",
    "RiskController",
    # Telemetry (Deferred 4, B2)
    "TelemetryEventType",
    "TelemetryLevel",
    "TelemetryConfig",
    "TelemetryEvent",
    "ProposalFields",
    "VerificationFields",
    "LLMCallFields",
    "AutonomousIterationFields",
    "ErrorFields",
    "ContinuityTraceFields",
    "ContinuityResultFields",
    "CostReport",
    "PerformanceReport",
    "AnchorStats",
    "ConvergenceReport",
    "LogStats",
    "StructuredLogger",
    "TelemetryBackend",
    "LoggingBackend",
    "TelemetryCollector",
    "analyze_costs",
    "analyze_performance",
    "analyze_convergence",
    "export_events",
    "get_collector",
    "get_telemetry_logger",
    "hash_prompt",
    # Instrumented Execution (AG2 Layer 0, Item #1)
    "EventKind",
    "ClaimModality",
    "AG2ClaimType",
    "DiffFinding",
    "ActorKind",
    "FindingSeverity",
    "InstrumentProfile",
    "Actor",
    "InstrumentEnvironment",
    "RepoState",
    "ModelSpec",
    "RunConfig",
    "RunInputs",
    "RunManifest",
    "InstrumentEvent",
    "ArtifactReceipt",
    "ClaimSource",
    "ClaimScope",
    "AG2Claim",
    "AG2ClaimDiffResult",
    "Waiver",
    "ReportFinding",
    "ReportProvenance",
    "AG2Report",
    "InstrumentConfig",
    "ArtifactStore",
    "RunStore",
    "EventWriter",
    "ClaimExtractor",
    "AG2ClaimDiffer",
    "ReportGenerator",
    "RunVerifier",
    "WaiverStore",
    "InstrumentSystem",
    "PytestParser",
    "MypyParser",
    "RuffParser",
    "DEFAULT_TOOL_PARSERS",
    # Slim Mode (AG2 Layer 0, Item #2)
    "SlimMode",
    "SlimStatus",
    "ContradictionError",
    "create_slim_mode",
    # Constraint Compiler (AG2 Layer 1, Item #3)
    "ConstraintKind",
    "ConstraintSeverity",
    "ScarClass",
    "ConstraintOutputFormat",
    "ResolvedConstraint",
    "ConstraintSource",
    "OverrideWarrant",
    "QuorumUnsatisfiedReceipt",
    "ConstraintBlock",
    "ConstraintCache",
    "ConstraintDiff",
    "classify_scar",
    "required_quorum",
    "check_warrant_quorum",
    "make_constraint_id",
    "compute_constraint_priority",
    "render_prompt_prefix",
    "compile_constraints",
    "diff_constraints",
    "clear_constraint_cache",
    "get_constraint_cache",
    # Detector Integration (AG2 Layer 1, Item #4)
    "PhaseFlag",
    "SignalQuality",
    "GovernorAction",
    "SignalKey",
    "RawDetectorSignal",
    "CollapsedSignal",
    "SignalPolicy",
    "SignalActionResult",
    "DetectorSignalFile",
    "DetectorIntegration",
    "collapse_signal",
    "map_signal_to_actions",
    "failure_safe_signal",
    "signal_to_constraints",
    "make_evidence_ref",
    "load_signal_file",
    "save_signal_file",
    # Commitment Transport (AG2 Layer 2, Item #5)
    "TransportModality",
    "CommitmentKind",
    "TransportOutcome",
    "TransportCommitment",
    "CommitmentTransport",
    "ShearReport",
    "TransportHistory",
    "extract_commitments",
    "validate_transport",
    "check_transport",
    "validate_compaction_transport",
    "validate_bridge_transport",
    "validate_constraint_transport",
    "make_transport_event",
    # Spectral Stability (AG2 Layer 2, Item #6)
    "KineticRegion",
    "GateVerdict",
    "GovernanceLayer",
    "CouplingHotspot",
    "AdjacencyViolation",
    "CouplingMatrix",
    "StabilityReport",
    "StabilityGate",
    "build_coupling_matrix",
    "check_adjacency",
    "classify_region",
    "determine_verdict",
    "find_hotspots",
    "compute_stability",
    "make_stability_event",
    # Scalar Collapse (AG2 Layer 2, Item #7)
    "CollapseRisk",
    "CollapseAction",
    "MetricSample",
    "CollapseSignals",
    "CollapseReport",
    "CollapseHistory",
    "CollapseDetector",
    "compute_signals",
    "compute_collapse_risk",
    "classify_collapse_risk",
    "determine_collapse_action",
    "detect_collapse",
    "make_collapse_event",
    "DEFAULT_METRICS",
    # CLI Chat (AG2 Layer 3, Item #8)
    "ChatConfig",
    "BackendInfo",
    "ChatResult",
    "CompareResult",
    "probe_backends",
    "probe_backend",
    "run_chat",
    "run_compare",
    "parse_backend_spec",
    "parse_backend_list",
    "format_chat_response",
    "format_chat_compare",
    "make_chat_event",
    # Document Governance (AG2 Layer 4, Item #10)
    "DocScope",
    "DocStatus",
    "LinkKind",
    "DocCheckSeverity",
    "DocLink",
    "GovDoc",
    "AuthorityClaim",
    "DocFinding",
    "DocCheckResult",
    "DocReceipt",
    "StalenessReport",
    "DocStore",
    "DocGovernor",
    "ExportConfig",
    "extract_authority_claims",
    "check_doc_authority",
    "check_doc_adjacency",
    "check_doc_links",
    "check_doc_staleness",
    "check_doc",
    "generate_frontmatter",
    "generate_sidecar",
    "make_doc_event",
    # Dashboard UX (AG2 Layer 4, Item #11)
    "StreamEventType",
    "RunVerdict",
    "RunState",
    "ControlRender",
    "CancelRequest",
    "StreamEvent",
    "RunTemplate",
    "BUILTIN_TEMPLATES",
    "ControlField",
    "UIAction",
    "BUILTIN_ACTIONS",
    "RunSummary",
    "DashboardSummary",
    "ReportSection",
    "RunReport",
    "DashboardStore",
    "build_controls_schema",
    "generate_run_report",
    "make_heartbeat",
    "make_progress",
    "make_dashboard_event",
    # WebUI Demo (AG2 Layer 4, Item #12)
    "DemoSurface",
    "StepAction",
    "DemoStatus",
    "DemoStep",
    "DemoScenario",
    "DemoManifest",
    "DemoStore",
    "BUILTIN_DEMOS",
    "FICTION_VIOLATION_DEMO",
    "CODE_GOVERNANCE_DEMO",
    "INTERFEROMETRY_DEMO",
    "generate_playwright_spec",
    "make_demo_event",
    # Admissibility Gate (AG2 Layer 2.1-A)
    "AdmitSeverity",
    "UnknownCategory",
    "ResolvableBy",
    "PushbackMode",
    "AssumptionStatus",
    "AdmitUnknown",
    "Assumption",
    "AdmissibilityAssessment",
    "AdmitWaiver",
    "AdmissibilityStore",
    "select_pushback_mode",
    "select_clarifying_questions",
    "assess_task",
    "check_invariant_f",
    "make_admissibility_event",
    # Coverage Metrics (AG2 Layer 2.1-A)
    "MetricSeverity",
    "VerificationStatus",
    "MetricClaim",
    "ClaimCoverage",
    "EfficiencyMetric",
    "CoverageSnapshot",
    "MetricsTracker",
    "MetricsStore",
    "compute_coverage",
    "compute_coverage_by_severity",
    "compute_efficiency",
    "compute_claim_coverage",
    "update_claim_status",
    "make_metrics_event",
    # Phase Control (AG2 Layer 2.1-A)
    "Phase",
    "TransitionResult",
    "PhaseBudget",
    "PhaseUsage",
    "NoveltyDebt",
    "PhaseRunState",
    "PhaseTransitionEvent",
    "PhaseController",
    "PhaseStore",
    "can_advance",
    "check_budget",
    "check_invariant_g",
    "make_phase_event",
    # Risk Function (AG2 Layer 2.1-B)
    "RiskLevel",
    "PolicyAction",
    "RiskSignal",
    "RiskWeights",
    "RiskComponents",
    "RiskAssessment",
    "ThresholdCrossing",
    "RiskState",
    "RiskStore",
    "compute_risk",
    "classify_risk",
    "apply_risk_policy",
    "assess_risk",
    "extract_untrusted_signal",
    "extract_evidence_gap",
    "extract_scope_signal",
    "extract_irreversibility_signal",
    "make_risk_event",
    # Coherence Budget (AG2 Layer 2.1-C)
    "CBIStatus",
    "ClosureDecision",
    "CBIClaimStatus",
    "CBIUnknownStatus",
    "InvariantID",
    "MetricID",
    "CBIClaim",
    "CBIUnknown",
    "CBIResult",
    "ClosureGateResult",
    "CoherenceBudgetStore",
    "compute_m1", "compute_m2", "compute_m3", "compute_m4",
    "compute_m5", "compute_m6", "compute_m7", "compute_m8",
    "compute_dt",
    "attenuate_epistemic",
    "compute_slow_hash",
    "compute_drift_distance",
    "compute_stability_score",
    "compute_soft_score",
    "compute_invariant_penalty",
    "classify_cbi",
    "compute_cbi",
    "compute_uncertainty",
    "check_closure_gate",
    "check_passivity",
    "confidence_cap",
    "make_cbi_event",
    # Mode Detection (AG2 Layer 2.1-C)
    "DomainMode",
    "DriftAction",
    "DriftPhase",
    "ModeObservation",
    "ModePosterior",
    "ModeDriftAlert",
    "ModeState",
    "ModeDetectionStore",
    "compute_mode_features",
    "update_mode_posterior",
    "compute_mode_drift",
    "check_mode_drift",
    "get_mode_profile",
    "observe_and_update",
    "make_mode_event",
    # Epistemic Evasion (AG2 Layer 2.1-C)
    "EvasionOperator",
    "EvasionFailureMode",
    "EvasionSeverity",
    "OperatorDetection",
    "EvasionResult",
    "EvasionState",
    "EvasionStore",
    "analyze_evasion",
    "check_invariant_j",
    "audit_governor_prompts",
    "select_coupling_question",
    "make_evasion_event",
    # Deployment Profiles (AG2 Layer 2.1-B)
    "AuthorityClass",
    "AuditLevel",
    "ProposalStatus",
    "RateLimit",
    "CapabilityToken",
    "DeploymentProfile",
    "ActionProposal",
    "DeploymentStore",
    "PUBLIC_PROFILE",
    "DELEGATED_PROFILE",
    "OPERATOR_PROFILE",
    "AUTONOMOUS_PROFILE",
    "BUILTIN_PROFILES",
    "check_tool_access",
    "check_invariant_b",
    "check_invariant_e",
    "issue_token",
    "propose_action",
    "make_deployment_event",
    # Measurement Integrity (AG2 Layer 2.1-B)
    "TrustLevel",
    "AlertType",
    "FreezeReason",
    "ToolOutput",
    "TrustResult",
    "MeasurementAlert",
    "MeasurementState",
    "MeasurementStore",
    "is_trusted",
    "detect_instruction_masquerade",
    "evaluate_output",
    "check_invariant_c",
    "make_measurement_event",
]

__version__ = "0.6.0"
