"""
Agent Governor for Agentic Development

A constraint system that makes AI coding agents production-safe by preventing
hallucination, maintaining architectural coherence, and enforcing evidence requirements.
"""

from .core import AgentGovernor
from .ledger import CodebaseLedger, Commitment, CommitID
from .validators import Validator, FileValidator, Evidence
from .types import ProposalResult, Contradiction

# SQLite-backed multi-agent components
from .storage import Storage, Lease, get_storage
from .ledgers_v2 import (
    Fact,
    Decision,
    SQLiteFactLedger,
    SQLiteDecisionLedger,
    ConflictError,
    get_ledgers,
)
from .permissions import (
    AgentPermissions,
    PermissionManager,
    PROFILES as PERMISSION_PROFILES,
    create_default_config,
)

# Task management
from .tasks import (
    Task,
    TaskStatus,
    Priority,
    Label,
    Milestone,
    TimeEntry,
    Session,
    TaskManager,
    get_task_manager,
)

# Audit graph
from .graph import (
    Node,
    Edge,
    NodeType,
    EdgeType,
    AuditGraph,
    GraphBuilder,
    build_graph,
)

# Epistemic governance
from .epistemic import (
    Provenance,
    EvidenceType,
    EvidenceRef,
    GroundedClaim,
    GroundedClaimStatus,
    ClaimStatus,
    QUORUM_TO_CLAIM_STATUS,
    project_quorum_status,
    PromotionResult,
    EpistemicLedger,
    DEFAULT_CONFIDENCE,
    MAX_PEER_CONFIDENCE,
    HIGH_CONFIDENCE_THRESHOLD,
    CascadeEvent,
    PremiseCheckResult,
    TransitionReason,
    StatusTransition,
    TransitionResult,
    VALID_TRANSITIONS,
    is_valid_transition,
)

# Regime detection
from .regime import (
    OperationalRegime,
    RegimeSignals,
    RegimeThresholds,
    RegimeDetector,
    RegimeMetrics,
    SignalCollector,
)

# Boil control
from .boil import (
    ControlMode,
    BoilPreset,
    DwellState,
    BoilEvent,
    BoilController,
    PRESETS,
    list_presets,
    get_preset,
)

# Jurisdictions
from .jurisdictions import (
    SpilloverPolicy,
    ContradictionPolicy,
    BudgetProfile,
    Jurisdiction,
    JurisdictionState,
    JurisdictionManager,
    register_jurisdiction,
    get_jurisdiction,
    list_jurisdictions,
    get_all_jurisdictions,
    create_factual_jurisdiction,
    create_speculative_jurisdiction,
    create_adversarial_jurisdiction,
    create_narrative_jurisdiction,
)

# Security verifier
from .security import (
    VulnerabilityType,
    Severity,
    SecurityFinding,
    SecurityConfig,
    SecurityVerifier,
    quick_scan,
)

# Watch mode
from .watch import (
    FileState,
    FileChange,
    WatchEvent,
    WatchConfig,
    FileWatcher,
    WatchSession,
    watch_directory,
)

# Claude Code hooks
from .claude_hooks import (
    HookConfig,
    install_claude_hooks,
    uninstall_claude_hooks,
    get_hook_status,
)

# Direction tracking (landmarks, commitments, Δt)
from .direction import (
    CommitmentType,
    AnchorType,
    RelationType,
    ViolationSeverity,
    Commitment,
    Anchor,
    Relation,
    Trajectory,
    DeltaT,
    Violation,
    Triangle,
    BeliefGraph,
    DirectionLedger,
    create_direction_ledger,
    create_fiction_anchors,
    create_nonfiction_anchors,
    create_thesis_commitment,
    create_chekhov_commitment,
)

# Failure provenance & constraint hysteresis
from .scars import (
    FailureProvenance,
    Scar,
    Shield,
    FailureEvent,
    ScarConfig,
    ScarLedger,
    MAX_STIFFNESS,
    MIN_STIFFNESS,
    DEFAULT_ANNEAL_FLOOR,
    create_scar_ledger,
    classify_failure,
)

# Grounding audit pipeline
from .audit import (
    GroundingStatus,
    AuditStage,
    FailureMode,
    AuditDecision,
    AuditSeverity,
    AssertionScope,
    ClaimRisk,
    AuditResolution,
    DetectionSignals,
    GroundingAudit,
    PolicyEntry,
    PolicyStore,
    AuditPipeline,
    quick_audit,
    create_pipeline,
)

# Ultrastability (S₁ adaptive control)
from .ultrastability import (
    AdaptationVerdict,
    Pathology,
    ParameterDirection,
    ParameterSpec,
    RegulatoryParameters,
    EpochObservation,
    AdaptationRecord,
    AdaptationHistory,
    AdaptationTrigger,
    PathologyDetector,
    AdaptationDecision,
    UltrastabilityController,
    create_controller,
    create_default_parameters,
    observe_and_consider,
)

# Multi-agent routing
from .routing import (
    ModelTier,
    ComplexityEstimate,
    ComplexityEstimator,
    ModelCapabilities,
    ModelStatus,
    ModelRegistry,
    TaskRecord,
    TaskHistory,
    RoutingDecision,
    RoutingConfig,
    Router,
    create_router,
    estimate_complexity,
    recommend_tier,
)

# Homeostat (exploration budgets, adaptive gain scheduling)
from .homeostat import (
    HomeostatMode,
    ExplorationContext,
    EpistemicVitals,
    EpistemicSetpoints,
    TuningDelta,
    ExplorationBudget,
    ExplorationProfile,
    TuningGains,
    TuningClamps,
    ObservationRecord,
    Homeostat,
    EXPLORATION_PROFILES,
    get_profile,
    list_profiles,
    create_homeostat,
    create_setpoints,
    observe_and_tune,
)

# Coupling (Homeostat → Ultrastability one-way protocol)
from .coupling import (
    IntentVerdict,
    ParameterMapping,
    ParameterProposal,
    TuningIntent,
    ChangeResult,
    IntentOutcome,
    CouplingConfig,
    GovernorCoupling,
    DEFAULT_MAPPINGS,
    create_coupling,
)

# Drift detection (temporal asymmetry defense)
from .drift import (
    DriftFailureMode,
    DriftAlert,
    PremiseRecord,
    AgentActivity,
    DriftSignals,
    DriftThresholds,
    QuarantineConfig,
    PremiseQuarantine,
    DriftDetector,
    create_drift_detector,
    detect_drift,
)

# Strict programmer mode
from .strict import (
    ClaimCategory,
    CommitLevel,
    RiskLevel,
    ClaimRequirement,
    DEFAULT_REQUIREMENTS,
    DependencyContext,
    StrictPolicy,
    ClaimEvaluation,
    StrictModeGate,
    create_strict_policy,
    create_strict_setpoints,
    create_strict_boil_preset,
    create_strict_s1_overrides,
    create_strict_gate,
    quick_evaluate,
)

# Claim signal extraction
from .claim_signals import (
    SignalCategory,
    SignalMatch,
    ExtractionResult,
    ExtractionConfig,
    SignalExtractor,
    extract_signals,
    scan_text,
    has_implicit_claims,
    assertiveness_score,
    register_signals,
)

# TTL enforcement (recency decay)
from .ttl import (
    VolatilityClass,
    DecayAction,
    TTLPolicy,
    TrackedClaim,
    DecayEvent,
    RevalidationEntry,
    TTLManager,
    DEFAULT_POLICIES as DEFAULT_TTL_POLICIES,
    create_ttl_manager,
    # Layer 5: Revalidation orchestration
    RevalidationResult,
    RevalidationRun,
    RevalidationOrchestrator,
    create_revalidation_orchestrator,
)

# Dissent ledger (contradiction persistence)
from .dissent import (
    ObjectionSeverity,
    ObjectionStatus,
    BlockVerdict,
    EvidencePointer,
    Objection,
    ConfidenceSnapshot,
    ClaimDissentSummary,
    DissentLedger,
    create_dissent_ledger,
)

# Config profiles
from .profiles import (
    ProfileSettings,
    ProfileManager,
    BUILTIN_PROFILES,
    apply_profile,
    get_profile_manager,
)

# Claim diff (epistemic state change detection)
from .claim_diff import (
    MutationType,
    ViolationType,
    MUTATION_SEVERITY,
    ClaimSnapshot,
    LedgerSnapshot,
    MutationEvent,
    ClaimPair,
    Violation as ClaimDiffViolation,
    DiffResult,
    DiffHistory,
    ClaimDiffer,
    snapshot_ledger,
    diff_snapshots,
    detect_laundering,
    detect_confidence_drift,
)

# Quorum state machine (multi-agent consensus)
from .quorum import (
    ClaimType as QuorumClaimType,
    VoteVerdict,
    QuorumStatus,
    QuorumPolicy,
    Vote,
    QuorumState,
    QuorumManager,
    DEFAULT_POLICIES as DEFAULT_QUORUM_POLICIES,
    create_quorum_manager,
    get_default_policy,
    RiskLevel as QuorumRiskLevel,
    TERMINAL_STATES,
    compute_fingerprint,
    # Layer 5: Roles & Scheduling
    AgentRole,
    RoleBudget,
    DEFAULT_ROLE_BUDGETS,
)

# Cooperative redundancy (independence scoring)
from .independence import (
    MethodSignature,
    IndependenceResult,
    IndependenceScorer,
    pairwise_jaccard,
    independence_score,
    is_independent_support,
)

# Semantic variety (post-commit text transform)
from .semvar import (
    MeaningTag,
    Register,
    PhraseEntry,
    SemVarConfig,
    PhraseMatch,
    TextInvariants,
    SemVarResult,
    PhraseBank,
    CooldownTracker,
    SemanticDiffGuard,
    SemVarEngine,
    extract_invariants,
)

# Puppet mode (persona pinning, semantic safety)
from .puppet import (
    CertaintyLevel,
    TagPosition,
    AnswerMode,
    DiffRuleId,
    DiffWarnId,
    RenderVerdict,
    FormattingRules,
    VoiceConstraints,
    HedgePolicy,
    VolatilityPolicy,
    EpistemicPosture,
    BehavioralConstraints,
    RoleDisclaimer,
    SafetyOverrides,
    PuppetProfile,
    SkeletonAtom,
    AnswerSkeleton,
    DiffViolation,
    DiffWarning,
    DiffGuardResult,
    PuppetRenderResult,
    PuppetDiffGuard,
    PuppetRenderer,
    PuppetRegistry,
    create_puppet_registry,
    create_puppet_renderer,
    render_with_puppet,
)

# Evidence persistence (Layer 1)
from .evidence_store import (
    RunProvenance,
    EvidenceStore,
    create_evidence_store,
)

# Tainted claim similarity (recurrence detection)
from .taint import (
    TaintType,
    FingerprintMethod,
    TaintVerdict,
    Fingerprint,
    TaintedClaim,
    TaintMatch,
    TaintCheckResult,
    TaintEvent,
    TaintConfig,
    TaintIndex,
    normalize as taint_normalize,
    fingerprint as taint_fingerprint,
    score as taint_score,
    create_taint_index,
    check_claim,
    taint_claim,
)

# Auto-tuning (threshold learning, reset tracking, setpoint calibration, budget sweep)
from .auto_tuning import (
    ResetType,
    TuningSuggestionKind,
    SweepMetric,
    CalibrationPhase,
    SignalDistribution,
    RegimeDistributions,
    ThresholdSuggestion,
    ThresholdAnalysis,
    ThresholdTuner,
    ResetRecord,
    ResetReport,
    ResetTracker,
    BaselineProfile,
    CalibrationResult,
    SetpointCalibrator,
    SweepPoint,
    SweepResult,
    BudgetSweeper,
    AutoTuner,
    create_auto_tuner,
    analyze_thresholds_from_metrics,
)

# Convergence tuning (offline system identification + proposal engine)
from .convergence_tuning import (
    TuningMode, TuningConfidence,
    ProposalStatus as TuningProposalStatus,
    ChangeSetType, RefactorSuggestionType, RollbackMetric, RollbackOperator,
    Regime as TuningRegime, Scope as TuningScope,
    TimeRange as TuningTimeRange, EvidenceWindow as TuningEvidenceWindow,
    ChangeParameterUpdate, ChangePatternUpdate, ChangeRefactorSuggestion,
    ChangeSet as TuningChangeSet,
    HardGuards, ObjectiveConstraints, Constraints as TuningConstraints,
    MetricsBlock, PredictedImpact, SummaryTable, ExampleEpisode,
    InterferenceEdge as TuningInterferenceEdge, SupportingEvidence,
    RollbackTrigger, TrialScope, EvaluationSet, TrialPlan,
    Approval as TuningApproval, TuningProposal, TuningApply,
    ProposalStore, PerAnchorAnalysis, ActionEffectiveness, TuningOpportunity,
    ConvergenceAnalyzer, AdmissibilityResult,
    check_regime_match, check_strength_non_regression,
    check_objective_constraints, check_trial_requirements,
    check_determinism_hygiene, check_admissibility,
    ConvergenceTuner, create_convergence_tuner,
    ACTION_AGGRESSIVENESS,
)

# Sybil resistance (bloc detection, Neff, origin budgets)
from .sybil import (
    SybilEventType,
    ProvenanceVector,
    Bloc,
    NeffResult,
    OriginBudget,
    SybilEvent,
    SybilConfig,
    BlocDetector,
    OriginBudgetTracker,
    SybilDetector,
    create_sybil_detector,
    compute_neff,
)

# Research mode (non-convergent epistemic control)
from .research import (
    HypothesisState,
    TerminalStateType,
    PromotionBlockReason,
    ResearchConfig,
    EvidenceImpulse,
    Hypothesis,
    TerminalState,
    EntropyCheckResult,
    DominanceCheckResult,
    DeltaTCheckResult,
    EntropyMonitor,
    DominanceMonitor,
    TimescaleMonitor,
    ResearchLedger,
    create_research_ledger,
    create_research_config,
)

# Continuity enforcement (Deferred 5: closed-loop generation control)
from .continuity import (
    AnchorType as ContinuityAnchorType,
    Severity as ContinuitySeverity,
    RecommendedAction,
    CorrectionLevel,
    Anchor as ContinuityAnchor,
    Violation as ContinuityViolation,
    ContinuityReport,
    AttemptLog,
    CorrectionConfig,
    ConvergenceBudget,
    ConvergenceResult,
    GenerationProvider,
    AnchorRegistry,
    ContinuityChecker,
    CorrectionLadder,
    DEFAULT_LADDER,
    ConvergenceExecutor,
    create_registry as create_continuity_registry,
    create_checker as create_continuity_checker,
    create_ladder as create_continuity_ladder,
    create_convergence_executor,
    check_output as check_continuity_output,
)

# Continuity bridges (mode-specific anchor integration)
from .continuity_bridges import (
    anchors_from_fiction_bible,
    anchors_from_characters,
    anchors_from_banned_tropes,
    anchors_from_world_rules,
    anchors_from_tone_settings,
    anchors_from_nonfiction_corpus,
    anchors_from_concepts,
    anchors_from_positions,
    anchors_from_puppet_profile,
)

# Governor adapters (Phase A4)
from .adapters import (
    AdapterFinding,
    AdapterConfig,
    ContentCheckFn,
    security_invariant,
    cfi_invariant,
    fiction_invariant,
    nonfiction_citation_invariant,
    tone_invariant,
    continuity_invariant,
    content_invariant,
    build_adapter_set,
)

# Invariant store (Deferred 1: invariant management)
from .invariant_store import (
    InvariantSpec,
    InvariantStore,
    VALID_KINDS,
)

# Context manager (Deferred 2: Web UI) - no external deps
from .context_manager import (
    GovernorContext,
    GovernorContextManager,
    VALID_MODES as CONTEXT_VALID_MODES,
)

# Chat bridge (Deferred 2: Web UI) - requires httpx (webui optional dep)
try:
    from .chat_bridge import (
        ChatMessage as BridgeChatMessage,
        ChatResponse as BridgeChatResponse,
        ChatChunk,
        ChatBackend,
        ChatBridge,
        GovernorHooks as BridgeGovernorHooks,
        OllamaBackend,
        AnthropicBackend,
        create_backend,
    )
except ImportError:
    pass

# Telemetry (Deferred 4, B2)
from .telemetry import (
    TelemetryEventType,
    TelemetryLevel,
    TelemetryConfig,
    TelemetryEvent,
    ProposalFields,
    VerificationFields,
    LLMCallFields,
    AutonomousIterationFields,
    ErrorFields,
    ContinuityTraceFields,
    ContinuityResultFields,
    CostReport,
    PerformanceReport,
    AnchorStats,
    ConvergenceReport,
    LogStats,
    StructuredLogger,
    TelemetryBackend,
    LoggingBackend,
    TelemetryCollector,
    analyze_costs,
    analyze_performance,
    analyze_convergence,
    export_events,
    get_collector,
    get_logger as get_telemetry_logger,
    hash_prompt,
)

# Autonomous execution (Phase A1-A2)
from .spine import (
    Spine,
    SpineViolation,
    SpineCheckResult,
    SpineManager,
)
from .invariants import (
    InvariantType,
    InvariantResult,
    Invariant,
    InvariantSet,
    InvariantLibrary,
)
from .execution import (
    StopReason,
    ExecutionStatus,
    ExecutionBudget,
    ExecutionUsage,
    ExecutionState,
    SessionManager,
)
from .executor import (
    StepResult,
    ExecutorConfig,
    ExecutionEvent,
    AutonomousExecutor,
)

__all__ = [
    # Legacy v0.1
    "AgentGovernor",
    "CodebaseLedger",
    "Commitment",
    "CommitID",
    "Validator",
    "FileValidator",
    "Evidence",
    "ProposalResult",
    "Contradiction",
    # Multi-agent (v2)
    "Storage",
    "Lease",
    "get_storage",
    "Fact",
    "Decision",
    "SQLiteFactLedger",
    "SQLiteDecisionLedger",
    "ConflictError",
    "get_ledgers",
    # Permissions
    "AgentPermissions",
    "PermissionManager",
    "PERMISSION_PROFILES",
    "create_default_config",
    # Task management
    "Task",
    "TaskStatus",
    "Priority",
    "Label",
    "Milestone",
    "TimeEntry",
    "Session",
    "TaskManager",
    "get_task_manager",
    # Audit graph
    "Node",
    "Edge",
    "NodeType",
    "EdgeType",
    "AuditGraph",
    "GraphBuilder",
    "build_graph",
    # Epistemic governance
    "Provenance",
    "EvidenceType",
    "EvidenceRef",
    "GroundedClaim",
    "GroundedClaimStatus",
    "ClaimStatus",
    "QUORUM_TO_CLAIM_STATUS",
    "project_quorum_status",
    "PromotionResult",
    "EpistemicLedger",
    "DEFAULT_CONFIDENCE",
    "MAX_PEER_CONFIDENCE",
    "HIGH_CONFIDENCE_THRESHOLD",
    "CascadeEvent",
    "PremiseCheckResult",
    "TransitionReason",
    "StatusTransition",
    "TransitionResult",
    "VALID_TRANSITIONS",
    "is_valid_transition",
    # Regime detection
    "OperationalRegime",
    "RegimeSignals",
    "RegimeThresholds",
    "RegimeDetector",
    "RegimeMetrics",
    "SignalCollector",
    # Boil control
    "ControlMode",
    "BoilPreset",
    "DwellState",
    "BoilEvent",
    "BoilController",
    "PRESETS",
    "list_presets",
    "get_preset",
    # Jurisdictions
    "SpilloverPolicy",
    "ContradictionPolicy",
    "BudgetProfile",
    "Jurisdiction",
    "JurisdictionState",
    "JurisdictionManager",
    "register_jurisdiction",
    "get_jurisdiction",
    "list_jurisdictions",
    "get_all_jurisdictions",
    "create_factual_jurisdiction",
    "create_speculative_jurisdiction",
    "create_adversarial_jurisdiction",
    "create_narrative_jurisdiction",
    # Security verifier
    "VulnerabilityType",
    "Severity",
    "SecurityFinding",
    "SecurityConfig",
    "SecurityVerifier",
    "quick_scan",
    # Watch mode
    "FileState",
    "FileChange",
    "WatchEvent",
    "WatchConfig",
    "FileWatcher",
    "WatchSession",
    "watch_directory",
    # Claude Code hooks
    "HookConfig",
    "install_claude_hooks",
    "uninstall_claude_hooks",
    "get_hook_status",
    # Direction tracking
    "CommitmentType",
    "AnchorType",
    "RelationType",
    "ViolationSeverity",
    "Commitment",
    "Anchor",
    "Relation",
    "Trajectory",
    "DeltaT",
    "Violation",
    "Triangle",
    "BeliefGraph",
    "DirectionLedger",
    "create_direction_ledger",
    "create_fiction_anchors",
    "create_nonfiction_anchors",
    "create_thesis_commitment",
    "create_chekhov_commitment",
    # Failure provenance & constraint hysteresis
    "FailureProvenance",
    "Scar",
    "Shield",
    "FailureEvent",
    "ScarConfig",
    "ScarLedger",
    "MAX_STIFFNESS",
    "MIN_STIFFNESS",
    "DEFAULT_ANNEAL_FLOOR",
    "create_scar_ledger",
    "classify_failure",
    # Grounding audit pipeline
    "GroundingStatus",
    "AuditStage",
    "FailureMode",
    "AuditDecision",
    "AuditSeverity",
    "AssertionScope",
    "ClaimRisk",
    "AuditResolution",
    "DetectionSignals",
    "GroundingAudit",
    "PolicyEntry",
    "PolicyStore",
    "AuditPipeline",
    "quick_audit",
    "create_pipeline",
    # Ultrastability (S₁ adaptive control)
    "AdaptationVerdict",
    "Pathology",
    "ParameterDirection",
    "ParameterSpec",
    "RegulatoryParameters",
    "EpochObservation",
    "AdaptationRecord",
    "AdaptationHistory",
    "AdaptationTrigger",
    "PathologyDetector",
    "AdaptationDecision",
    "UltrastabilityController",
    "create_controller",
    "create_default_parameters",
    "observe_and_consider",
    # Multi-agent routing
    "ModelTier",
    "ComplexityEstimate",
    "ComplexityEstimator",
    "ModelCapabilities",
    "ModelStatus",
    "ModelRegistry",
    "TaskRecord",
    "TaskHistory",
    "RoutingDecision",
    "RoutingConfig",
    "Router",
    "create_router",
    "estimate_complexity",
    "recommend_tier",
    # Homeostat (exploration budgets)
    "HomeostatMode",
    "ExplorationContext",
    "EpistemicVitals",
    "EpistemicSetpoints",
    "TuningDelta",
    "ExplorationBudget",
    "ExplorationProfile",
    "TuningGains",
    "TuningClamps",
    "ObservationRecord",
    "Homeostat",
    "EXPLORATION_PROFILES",
    "get_profile",
    "list_profiles",
    "create_homeostat",
    "create_setpoints",
    "observe_and_tune",
    # Coupling (Homeostat → Ultrastability)
    "IntentVerdict",
    "ParameterMapping",
    "ParameterProposal",
    "TuningIntent",
    "ChangeResult",
    "IntentOutcome",
    "GovernorCoupling",
    "CouplingConfig",
    "DEFAULT_MAPPINGS",
    "create_coupling",
    # Drift detection (temporal asymmetry defense)
    "DriftFailureMode",
    "DriftAlert",
    "PremiseRecord",
    "AgentActivity",
    "DriftSignals",
    "DriftThresholds",
    "QuarantineConfig",
    "PremiseQuarantine",
    "DriftDetector",
    "create_drift_detector",
    "detect_drift",
    # Strict programmer mode
    "ClaimCategory",
    "CommitLevel",
    "RiskLevel",
    "ClaimRequirement",
    "DEFAULT_REQUIREMENTS",
    "DependencyContext",
    "StrictPolicy",
    "ClaimEvaluation",
    "StrictModeGate",
    "create_strict_policy",
    "create_strict_setpoints",
    "create_strict_boil_preset",
    "create_strict_s1_overrides",
    "create_strict_gate",
    "quick_evaluate",
    # Claim signal extraction
    "SignalCategory",
    "SignalMatch",
    "ExtractionResult",
    "ExtractionConfig",
    "SignalExtractor",
    "extract_signals",
    "scan_text",
    "has_implicit_claims",
    "assertiveness_score",
    "register_signals",
    # TTL enforcement (recency decay)
    "VolatilityClass",
    "DecayAction",
    "TTLPolicy",
    "TrackedClaim",
    "DecayEvent",
    "RevalidationEntry",
    "TTLManager",
    "DEFAULT_TTL_POLICIES",
    "create_ttl_manager",
    "RevalidationResult",
    "RevalidationRun",
    "RevalidationOrchestrator",
    "create_revalidation_orchestrator",
    # Dissent ledger (contradiction persistence)
    "ObjectionSeverity",
    "ObjectionStatus",
    "BlockVerdict",
    "EvidencePointer",
    "Objection",
    "ConfidenceSnapshot",
    "ClaimDissentSummary",
    "DissentLedger",
    "create_dissent_ledger",
    # Config profiles
    "ProfileSettings",
    "ProfileManager",
    "BUILTIN_PROFILES",
    "apply_profile",
    "get_profile_manager",
    # Claim diff (epistemic state change detection)
    "MutationType",
    "ViolationType",
    "MUTATION_SEVERITY",
    "ClaimSnapshot",
    "LedgerSnapshot",
    "MutationEvent",
    "ClaimPair",
    "ClaimDiffViolation",
    "DiffResult",
    "DiffHistory",
    "ClaimDiffer",
    "snapshot_ledger",
    "diff_snapshots",
    "detect_laundering",
    "detect_confidence_drift",
    # Quorum state machine (multi-agent consensus)
    "QuorumClaimType",
    "VoteVerdict",
    "QuorumStatus",
    "QuorumPolicy",
    "Vote",
    "QuorumState",
    "QuorumManager",
    "DEFAULT_QUORUM_POLICIES",
    "create_quorum_manager",
    "get_default_policy",
    "QuorumRiskLevel",
    "TERMINAL_STATES",
    "compute_fingerprint",
    "AgentRole",
    "RoleBudget",
    "DEFAULT_ROLE_BUDGETS",
    # Cooperative redundancy (independence scoring)
    "MethodSignature",
    "IndependenceResult",
    "IndependenceScorer",
    "pairwise_jaccard",
    "independence_score",
    "is_independent_support",
    # Semantic variety (post-commit text transform)
    "MeaningTag",
    "Register",
    "PhraseEntry",
    "SemVarConfig",
    "PhraseMatch",
    "TextInvariants",
    "SemVarResult",
    "PhraseBank",
    "CooldownTracker",
    "SemanticDiffGuard",
    "SemVarEngine",
    "extract_invariants",
    # Puppet mode (persona pinning, semantic safety)
    "CertaintyLevel",
    "TagPosition",
    "AnswerMode",
    "DiffRuleId",
    "DiffWarnId",
    "RenderVerdict",
    "FormattingRules",
    "VoiceConstraints",
    "HedgePolicy",
    "VolatilityPolicy",
    "EpistemicPosture",
    "BehavioralConstraints",
    "RoleDisclaimer",
    "SafetyOverrides",
    "PuppetProfile",
    "SkeletonAtom",
    "AnswerSkeleton",
    "DiffViolation",
    "DiffWarning",
    "DiffGuardResult",
    "PuppetRenderResult",
    "PuppetDiffGuard",
    "PuppetRenderer",
    "PuppetRegistry",
    "create_puppet_registry",
    "create_puppet_renderer",
    "render_with_puppet",
    # Evidence persistence (Layer 1)
    "RunProvenance",
    "EvidenceStore",
    "create_evidence_store",
    # Tainted claim similarity (recurrence detection)
    "TaintType",
    "FingerprintMethod",
    "TaintVerdict",
    "Fingerprint",
    "TaintedClaim",
    "TaintMatch",
    "TaintCheckResult",
    "TaintEvent",
    "TaintConfig",
    "TaintIndex",
    "taint_normalize",
    "taint_fingerprint",
    "taint_score",
    "create_taint_index",
    "check_claim",
    "taint_claim",
    # Auto-tuning (threshold learning, reset tracking, calibration, sweep)
    "ResetType",
    "TuningSuggestionKind",
    "SweepMetric",
    "CalibrationPhase",
    "SignalDistribution",
    "RegimeDistributions",
    "ThresholdSuggestion",
    "ThresholdAnalysis",
    "ThresholdTuner",
    "ResetRecord",
    "ResetReport",
    "ResetTracker",
    "BaselineProfile",
    "CalibrationResult",
    "SetpointCalibrator",
    "SweepPoint",
    "SweepResult",
    "BudgetSweeper",
    "AutoTuner",
    "create_auto_tuner",
    "analyze_thresholds_from_metrics",
    # Convergence tuning (offline system identification + proposal engine)
    "TuningMode",
    "TuningConfidence",
    "TuningProposalStatus",
    "ChangeSetType",
    "RefactorSuggestionType",
    "RollbackMetric",
    "RollbackOperator",
    "TuningRegime",
    "TuningScope",
    "TuningTimeRange",
    "TuningEvidenceWindow",
    "ChangeParameterUpdate",
    "ChangePatternUpdate",
    "ChangeRefactorSuggestion",
    "TuningChangeSet",
    "HardGuards",
    "ObjectiveConstraints",
    "TuningConstraints",
    "MetricsBlock",
    "PredictedImpact",
    "SummaryTable",
    "ExampleEpisode",
    "TuningInterferenceEdge",
    "SupportingEvidence",
    "RollbackTrigger",
    "TrialScope",
    "EvaluationSet",
    "TrialPlan",
    "TuningApproval",
    "TuningProposal",
    "TuningApply",
    "ProposalStore",
    "PerAnchorAnalysis",
    "ActionEffectiveness",
    "TuningOpportunity",
    "ConvergenceAnalyzer",
    "AdmissibilityResult",
    "check_regime_match",
    "check_strength_non_regression",
    "check_objective_constraints",
    "check_trial_requirements",
    "check_determinism_hygiene",
    "check_admissibility",
    "ConvergenceTuner",
    "create_convergence_tuner",
    "ACTION_AGGRESSIVENESS",
    # Sybil resistance (bloc detection, Neff, origin budgets)
    "SybilEventType",
    "ProvenanceVector",
    "Bloc",
    "NeffResult",
    "OriginBudget",
    "SybilEvent",
    "SybilConfig",
    "BlocDetector",
    "OriginBudgetTracker",
    "SybilDetector",
    "create_sybil_detector",
    "compute_neff",
    # Research mode (non-convergent epistemic control)
    "HypothesisState",
    "TerminalStateType",
    "PromotionBlockReason",
    "ResearchConfig",
    "EvidenceImpulse",
    "Hypothesis",
    "TerminalState",
    "EntropyCheckResult",
    "DominanceCheckResult",
    "DeltaTCheckResult",
    "EntropyMonitor",
    "DominanceMonitor",
    "TimescaleMonitor",
    "ResearchLedger",
    "create_research_ledger",
    "create_research_config",
    # Continuity enforcement (Deferred 5)
    "ContinuityAnchorType",
    "ContinuitySeverity",
    "RecommendedAction",
    "CorrectionLevel",
    "ContinuityAnchor",
    "ContinuityViolation",
    "ContinuityReport",
    "AttemptLog",
    "CorrectionConfig",
    "ConvergenceBudget",
    "ConvergenceResult",
    "GenerationProvider",
    "AnchorRegistry",
    "ContinuityChecker",
    "CorrectionLadder",
    "DEFAULT_LADDER",
    "ConvergenceExecutor",
    "create_continuity_registry",
    "create_continuity_checker",
    "create_continuity_ladder",
    "create_convergence_executor",
    "check_continuity_output",
    # Continuity bridges (mode-specific anchor integration)
    "anchors_from_fiction_bible",
    "anchors_from_characters",
    "anchors_from_banned_tropes",
    "anchors_from_world_rules",
    "anchors_from_tone_settings",
    "anchors_from_nonfiction_corpus",
    "anchors_from_concepts",
    "anchors_from_positions",
    "anchors_from_puppet_profile",
    # Governor adapters (Phase A4)
    "AdapterFinding",
    "AdapterConfig",
    "ContentCheckFn",
    "security_invariant",
    "cfi_invariant",
    "fiction_invariant",
    "nonfiction_citation_invariant",
    "tone_invariant",
    "continuity_invariant",
    "content_invariant",
    "build_adapter_set",
    # Invariant store (Deferred 1)
    "InvariantSpec",
    "InvariantStore",
    "VALID_KINDS",
    # Context manager & chat bridge (Deferred 2: Web UI)
    "GovernorContext",
    "GovernorContextManager",
    "CONTEXT_VALID_MODES",
    "BridgeChatMessage",
    "BridgeChatResponse",
    "ChatChunk",
    "ChatBackend",
    "ChatBridge",
    "BridgeGovernorHooks",
    "OllamaBackend",
    "AnthropicBackend",
    "create_backend",
    # Autonomous execution (Phase A1-A2)
    "Spine",
    "SpineViolation",
    "SpineCheckResult",
    "SpineManager",
    "InvariantType",
    "InvariantResult",
    "Invariant",
    "InvariantSet",
    "InvariantLibrary",
    "StopReason",
    "ExecutionStatus",
    "ExecutionBudget",
    "ExecutionUsage",
    "ExecutionState",
    "SessionManager",
    "StepResult",
    "ExecutorConfig",
    "ExecutionEvent",
    "AutonomousExecutor",
    # Telemetry (Deferred 4, B2)
    "TelemetryEventType",
    "TelemetryLevel",
    "TelemetryConfig",
    "TelemetryEvent",
    "ProposalFields",
    "VerificationFields",
    "LLMCallFields",
    "AutonomousIterationFields",
    "ErrorFields",
    "ContinuityTraceFields",
    "ContinuityResultFields",
    "CostReport",
    "PerformanceReport",
    "AnchorStats",
    "ConvergenceReport",
    "LogStats",
    "StructuredLogger",
    "TelemetryBackend",
    "LoggingBackend",
    "TelemetryCollector",
    "analyze_costs",
    "analyze_performance",
    "analyze_convergence",
    "export_events",
    "get_collector",
    "get_telemetry_logger",
    "hash_prompt",
]

__version__ = "0.6.0"
